// Comprehensive word list organized by categories
// Each entry: { word: 'piano', theme: 'instrument', category: 'music' }
// Themes are intentionally vague to make the impostor role more challenging

const WORDS = [
  // --- Food & Drinks (100+ words) ---
  { word: 'chocolate', theme: 'dessert', category: 'food' },
  { word: 'sushi', theme: 'dish', category: 'food' },
  { word: 'pizza', theme: 'meal', category: 'food' },
  { word: 'hamburger', theme: 'meal', category: 'food' },
  { word: 'pancake', theme: 'breakfast', category: 'food' },
  { word: 'spaghetti', theme: 'pasta', category: 'food' },
  { word: 'taco', theme: 'meal', category: 'food' },
  { word: 'ice cream', theme: 'dessert', category: 'food' },
  { word: 'salad', theme: 'dish', category: 'food' },
  { word: 'croissant', theme: 'pastry', category: 'food' },
  { word: 'ramen', theme: 'noodles', category: 'food' },
  { word: 'soup', theme: 'dish', category: 'food' },
  { word: 'burrito', theme: 'meal', category: 'food' },
  { word: 'donut', theme: 'pastry', category: 'food' },
  { word: 'waffle', theme: 'breakfast', category: 'food' },
  { word: 'curry', theme: 'dish', category: 'food' },
  { word: 'sandwich', theme: 'meal', category: 'food' },
  { word: 'steak', theme: 'meat', category: 'food' },
  { word: 'bacon', theme: 'meat', category: 'food' },
  { word: 'chicken', theme: 'meat', category: 'food' },
  { word: 'salmon', theme: 'fish', category: 'food' },
  { word: 'shrimp', theme: 'seafood', category: 'food' },
  { word: 'lobster', theme: 'seafood', category: 'food' },
  { word: 'crab', theme: 'seafood', category: 'food' },
  { word: 'oyster', theme: 'seafood', category: 'food' },
  { word: 'cheese', theme: 'dairy', category: 'food' },
  { word: 'yogurt', theme: 'dairy', category: 'food' },
  { word: 'milk', theme: 'beverage', category: 'food' },
  { word: 'coffee', theme: 'beverage', category: 'food' },
  { word: 'tea', theme: 'beverage', category: 'food' },
  { word: 'juice', theme: 'beverage', category: 'food' },
  { word: 'soda', theme: 'beverage', category: 'food' },
  { word: 'smoothie', theme: 'beverage', category: 'food' },
  { word: 'milkshake', theme: 'beverage', category: 'food' },
  { word: 'lemonade', theme: 'beverage', category: 'food' },
  { word: 'apple', theme: 'fruit', category: 'food' },
  { word: 'banana', theme: 'fruit', category: 'food' },
  { word: 'orange', theme: 'fruit', category: 'food' },
  { word: 'strawberry', theme: 'berry', category: 'food' },
  { word: 'blueberry', theme: 'berry', category: 'food' },
  { word: 'grape', theme: 'fruit', category: 'food' },
  { word: 'watermelon', theme: 'fruit', category: 'food' },
  { word: 'pineapple', theme: 'fruit', category: 'food' },
  { word: 'mango', theme: 'fruit', category: 'food' },
  { word: 'avocado', theme: 'fruit', category: 'food' },
  { word: 'tomato', theme: 'vegetable', category: 'food' },
  { word: 'potato', theme: 'vegetable', category: 'food' },
  { word: 'carrot', theme: 'vegetable', category: 'food' },
  { word: 'broccoli', theme: 'vegetable', category: 'food' },
  { word: 'cucumber', theme: 'vegetable', category: 'food' },
  { word: 'onion', theme: 'vegetable', category: 'food' },
  { word: 'garlic', theme: 'vegetable', category: 'food' },
  { word: 'pepper', theme: 'vegetable', category: 'food' },
  { word: 'corn', theme: 'vegetable', category: 'food' },
  { word: 'rice', theme: 'grain', category: 'food' },
  { word: 'bread', theme: 'baked', category: 'food' },
  { word: 'bagel', theme: 'baked', category: 'food' },
  { word: 'muffin', theme: 'baked', category: 'food' },
  { word: 'cookie', theme: 'dessert', category: 'food' },
  { word: 'cake', theme: 'dessert', category: 'food' },
  { word: 'pie', theme: 'dessert', category: 'food' },
  { word: 'brownie', theme: 'dessert', category: 'food' },
  { word: 'candy', theme: 'sweet', category: 'food' },
  { word: 'gum', theme: 'sweet', category: 'food' },
  { word: 'popcorn', theme: 'snack', category: 'food' },
  { word: 'chips', theme: 'snack', category: 'food' },
  { word: 'pretzel', theme: 'snack', category: 'food' },
  { word: 'nachos', theme: 'snack', category: 'food' },
  { word: 'peanut butter', theme: 'spread', category: 'food' },
  { word: 'jelly', theme: 'spread', category: 'food' },
  { word: 'honey', theme: 'sweet', category: 'food' },
  { word: 'syrup', theme: 'sweet', category: 'food' },
  { word: 'ketchup', theme: 'condiment', category: 'food' },
  { word: 'mustard', theme: 'condiment', category: 'food' },
  { word: 'mayonnaise', theme: 'condiment', category: 'food' },
  { word: 'hot dog', theme: 'meal', category: 'food' },
  { word: 'french fries', theme: 'side', category: 'food' },
  { word: 'onion rings', theme: 'side', category: 'food' },
  { word: 'coleslaw', theme: 'side', category: 'food' },
  { word: 'mashed potatoes', theme: 'side', category: 'food' },
  { word: 'mac and cheese', theme: 'dish', category: 'food' },
  { word: 'lasagna', theme: 'pasta', category: 'food' },
  { word: 'ravioli', theme: 'pasta', category: 'food' },
  { word: 'fettuccine', theme: 'pasta', category: 'food' },
  { word: 'pho', theme: 'soup', category: 'food' },
  { word: 'dumpling', theme: 'dish', category: 'food' },
  { word: 'spring roll', theme: 'dish', category: 'food' },
  { word: 'tempura', theme: 'dish', category: 'food' },
  { word: 'kebab', theme: 'meat', category: 'food' },
  { word: 'falafel', theme: 'dish', category: 'food' },
  { word: 'hummus', theme: 'dip', category: 'food' },
  { word: 'guacamole', theme: 'dip', category: 'food' },
  { word: 'salsa', theme: 'dip', category: 'food' },
  { word: 'queso', theme: 'dip', category: 'food' },
  { word: 'enchilada', theme: 'dish', category: 'food' },
  { word: 'quesadilla', theme: 'dish', category: 'food' },
  { word: 'chimichanga', theme: 'dish', category: 'food' },
  { word: 'paella', theme: 'dish', category: 'food' },
  { word: 'risotto', theme: 'dish', category: 'food' },
  { word: 'gnocchi', theme: 'pasta', category: 'food' },
  { word: 'tiramisu', theme: 'dessert', category: 'food' },
  { word: 'gelato', theme: 'dessert', category: 'food' },
  { word: 'sorbet', theme: 'dessert', category: 'food' },
  { word: 'pudding', theme: 'dessert', category: 'food' },
  { word: 'cheesecake', theme: 'dessert', category: 'food' },
  { word: 'cupcake', theme: 'dessert', category: 'food' },
  { word: 'macaron', theme: 'dessert', category: 'food' },
  { word: 'eclair', theme: 'pastry', category: 'food' },
  { word: 'crepe', theme: 'pastry', category: 'food' },
  { word: 'baguette', theme: 'bread', category: 'food' },
  { word: 'pretzel', theme: 'bread', category: 'food' },
  { word: 'tortilla', theme: 'bread', category: 'food' },
  { word: 'naan', theme: 'bread', category: 'food' },
  { word: 'pita', theme: 'bread', category: 'food' },

  // --- Animals (100+ words) ---
  { word: 'elephant', theme: 'mammal', category: 'animals' },
  { word: 'penguin', theme: 'bird', category: 'animals' },
  { word: 'dolphin', theme: 'mammal', category: 'animals' },
  { word: 'giraffe', theme: 'mammal', category: 'animals' },
  { word: 'lion', theme: 'mammal', category: 'animals' },
  { word: 'panda', theme: 'mammal', category: 'animals' },
  { word: 'octopus', theme: 'sea creature', category: 'animals' },
  { word: 'butterfly', theme: 'insect', category: 'animals' },
  { word: 'kangaroo', theme: 'mammal', category: 'animals' },
  { word: 'owl', theme: 'bird', category: 'animals' },
  { word: 'tiger', theme: 'mammal', category: 'animals' },
  { word: 'shark', theme: 'fish', category: 'animals' },
  { word: 'whale', theme: 'mammal', category: 'animals' },
  { word: 'koala', theme: 'mammal', category: 'animals' },
  { word: 'sloth', theme: 'mammal', category: 'animals' },
  { word: 'cheetah', theme: 'mammal', category: 'animals' },
  { word: 'leopard', theme: 'mammal', category: 'animals' },
  { word: 'jaguar', theme: 'mammal', category: 'animals' },
  { word: 'panther', theme: 'mammal', category: 'animals' },
  { word: 'bear', theme: 'mammal', category: 'animals' },
  { word: 'wolf', theme: 'mammal', category: 'animals' },
  { word: 'fox', theme: 'mammal', category: 'animals' },
  { word: 'deer', theme: 'mammal', category: 'animals' },
  { word: 'moose', theme: 'mammal', category: 'animals' },
  { word: 'elk', theme: 'mammal', category: 'animals' },
  { word: 'buffalo', theme: 'mammal', category: 'animals' },
  { word: 'bison', theme: 'mammal', category: 'animals' },
  { word: 'zebra', theme: 'mammal', category: 'animals' },
  { word: 'hippo', theme: 'mammal', category: 'animals' },
  { word: 'rhino', theme: 'mammal', category: 'animals' },
  { word: 'gorilla', theme: 'primate', category: 'animals' },
  { word: 'chimpanzee', theme: 'primate', category: 'animals' },
  { word: 'orangutan', theme: 'primate', category: 'animals' },
  { word: 'monkey', theme: 'primate', category: 'animals' },
  { word: 'lemur', theme: 'primate', category: 'animals' },
  { word: 'raccoon', theme: 'mammal', category: 'animals' },
  { word: 'squirrel', theme: 'mammal', category: 'animals' },
  { word: 'chipmunk', theme: 'mammal', category: 'animals' },
  { word: 'beaver', theme: 'mammal', category: 'animals' },
  { word: 'otter', theme: 'mammal', category: 'animals' },
  { word: 'seal', theme: 'mammal', category: 'animals' },
  { word: 'walrus', theme: 'mammal', category: 'animals' },
  { word: 'polar bear', theme: 'mammal', category: 'animals' },
  { word: 'camel', theme: 'mammal', category: 'animals' },
  { word: 'llama', theme: 'mammal', category: 'animals' },
  { word: 'alpaca', theme: 'mammal', category: 'animals' },
  { word: 'horse', theme: 'mammal', category: 'animals' },
  { word: 'donkey', theme: 'mammal', category: 'animals' },
  { word: 'cow', theme: 'mammal', category: 'animals' },
  { word: 'pig', theme: 'mammal', category: 'animals' },
  { word: 'sheep', theme: 'mammal', category: 'animals' },
  { word: 'goat', theme: 'mammal', category: 'animals' },
  { word: 'rabbit', theme: 'mammal', category: 'animals' },
  { word: 'hamster', theme: 'mammal', category: 'animals' },
  { word: 'guinea pig', theme: 'mammal', category: 'animals' },
  { word: 'mouse', theme: 'mammal', category: 'animals' },
  { word: 'rat', theme: 'mammal', category: 'animals' },
  { word: 'bat', theme: 'mammal', category: 'animals' },
  { word: 'eagle', theme: 'bird', category: 'animals' },
  { word: 'hawk', theme: 'bird', category: 'animals' },
  { word: 'falcon', theme: 'bird', category: 'animals' },
  { word: 'parrot', theme: 'bird', category: 'animals' },
  { word: 'peacock', theme: 'bird', category: 'animals' },
  { word: 'flamingo', theme: 'bird', category: 'animals' },
  { word: 'swan', theme: 'bird', category: 'animals' },
  { word: 'duck', theme: 'bird', category: 'animals' },
  { word: 'goose', theme: 'bird', category: 'animals' },
  { word: 'chicken', theme: 'bird', category: 'animals' },
  { word: 'rooster', theme: 'bird', category: 'animals' },
  { word: 'turkey', theme: 'bird', category: 'animals' },
  { word: 'ostrich', theme: 'bird', category: 'animals' },
  { word: 'emu', theme: 'bird', category: 'animals' },
  { word: 'pelican', theme: 'bird', category: 'animals' },
  { word: 'seagull', theme: 'bird', category: 'animals' },
  { word: 'crow', theme: 'bird', category: 'animals' },
  { word: 'raven', theme: 'bird', category: 'animals' },
  { word: 'pigeon', theme: 'bird', category: 'animals' },
  { word: 'sparrow', theme: 'bird', category: 'animals' },
  { word: 'robin', theme: 'bird', category: 'animals' },
  { word: 'hummingbird', theme: 'bird', category: 'animals' },
  { word: 'woodpecker', theme: 'bird', category: 'animals' },
  { word: 'toucan', theme: 'bird', category: 'animals' },
  { word: 'crocodile', theme: 'reptile', category: 'animals' },
  { word: 'alligator', theme: 'reptile', category: 'animals' },
  { word: 'snake', theme: 'reptile', category: 'animals' },
  { word: 'lizard', theme: 'reptile', category: 'animals' },
  { word: 'iguana', theme: 'reptile', category: 'animals' },
  { word: 'gecko', theme: 'reptile', category: 'animals' },
  { word: 'chameleon', theme: 'reptile', category: 'animals' },
  { word: 'turtle', theme: 'reptile', category: 'animals' },
  { word: 'tortoise', theme: 'reptile', category: 'animals' },
  { word: 'frog', theme: 'amphibian', category: 'animals' },
  { word: 'toad', theme: 'amphibian', category: 'animals' },
  { word: 'salamander', theme: 'amphibian', category: 'animals' },
  { word: 'jellyfish', theme: 'sea creature', category: 'animals' },
  { word: 'starfish', theme: 'sea creature', category: 'animals' },
  { word: 'seahorse', theme: 'fish', category: 'animals' },
  { word: 'clownfish', theme: 'fish', category: 'animals' },
  { word: 'goldfish', theme: 'fish', category: 'animals' },
  { word: 'tuna', theme: 'fish', category: 'animals' },
  { word: 'swordfish', theme: 'fish', category: 'animals' },
  { word: 'stingray', theme: 'fish', category: 'animals' },
  { word: 'manta ray', theme: 'fish', category: 'animals' },
  { word: 'squid', theme: 'sea creature', category: 'animals' },
  { word: 'crab', theme: 'sea creature', category: 'animals' },
  { word: 'lobster', theme: 'sea creature', category: 'animals' },
  { word: 'shrimp', theme: 'sea creature', category: 'animals' },
  { word: 'snail', theme: 'mollusk', category: 'animals' },
  { word: 'slug', theme: 'mollusk', category: 'animals' },
  { word: 'worm', theme: 'invertebrate', category: 'animals' },
  { word: 'spider', theme: 'arachnid', category: 'animals' },
  { word: 'scorpion', theme: 'arachnid', category: 'animals' },
  { word: 'ant', theme: 'insect', category: 'animals' },
  { word: 'bee', theme: 'insect', category: 'animals' },
  { word: 'wasp', theme: 'insect', category: 'animals' },
  { word: 'hornet', theme: 'insect', category: 'animals' },
  { word: 'mosquito', theme: 'insect', category: 'animals' },
  { word: 'fly', theme: 'insect', category: 'animals' },
  { word: 'dragonfly', theme: 'insect', category: 'animals' },
  { word: 'grasshopper', theme: 'insect', category: 'animals' },
  { word: 'cricket', theme: 'insect', category: 'animals' },
  { word: 'beetle', theme: 'insect', category: 'animals' },
  { word: 'ladybug', theme: 'insect', category: 'animals' },
  { word: 'caterpillar', theme: 'insect', category: 'animals' },
  { word: 'moth', theme: 'insect', category: 'animals' },
  { word: 'firefly', theme: 'insect', category: 'animals' },

  // --- Nature & Weather (60+ words) ---
  { word: 'volcano', theme: 'landform', category: 'nature' },
  { word: 'rainforest', theme: 'biome', category: 'nature' },
  { word: 'mountain', theme: 'landform', category: 'nature' },
  { word: 'desert', theme: 'biome', category: 'nature' },
  { word: 'ocean', theme: 'water', category: 'nature' },
  { word: 'waterfall', theme: 'water', category: 'nature' },
  { word: 'glacier', theme: 'ice', category: 'nature' },
  { word: 'tornado', theme: 'weather', category: 'nature' },
  { word: 'earthquake', theme: 'disaster', category: 'nature' },
  { word: 'rainbow', theme: 'phenomenon', category: 'nature' },
  { word: 'thunderstorm', theme: 'weather', category: 'nature' },
  { word: 'tsunami', theme: 'disaster', category: 'nature' },
  { word: 'forest', theme: 'biome', category: 'nature' },
  { word: 'canyon', theme: 'landform', category: 'nature' },
  { word: 'cave', theme: 'landform', category: 'nature' },
  { word: 'river', theme: 'water', category: 'nature' },
  { word: 'lake', theme: 'water', category: 'nature' },
  { word: 'pond', theme: 'water', category: 'nature' },
  { word: 'stream', theme: 'water', category: 'nature' },
  { word: 'creek', theme: 'water', category: 'nature' },
  { word: 'swamp', theme: 'wetland', category: 'nature' },
  { word: 'marsh', theme: 'wetland', category: 'nature' },
  { word: 'island', theme: 'landform', category: 'nature' },
  { word: 'peninsula', theme: 'landform', category: 'nature' },
  { word: 'cliff', theme: 'landform', category: 'nature' },
  { word: 'valley', theme: 'landform', category: 'nature' },
  { word: 'hill', theme: 'landform', category: 'nature' },
  { word: 'plateau', theme: 'landform', category: 'nature' },
  { word: 'dune', theme: 'landform', category: 'nature' },
  { word: 'beach', theme: 'landform', category: 'nature' },
  { word: 'shore', theme: 'landform', category: 'nature' },
  { word: 'coast', theme: 'landform', category: 'nature' },
  { word: 'reef', theme: 'underwater', category: 'nature' },
  { word: 'iceberg', theme: 'ice', category: 'nature' },
  { word: 'avalanche', theme: 'disaster', category: 'nature' },
  { word: 'landslide', theme: 'disaster', category: 'nature' },
  { word: 'hurricane', theme: 'weather', category: 'nature' },
  { word: 'typhoon', theme: 'weather', category: 'nature' },
  { word: 'cyclone', theme: 'weather', category: 'nature' },
  { word: 'blizzard', theme: 'weather', category: 'nature' },
  { word: 'hailstorm', theme: 'weather', category: 'nature' },
  { word: 'lightning', theme: 'weather', category: 'nature' },
  { word: 'thunder', theme: 'weather', category: 'nature' },
  { word: 'fog', theme: 'weather', category: 'nature' },
  { word: 'mist', theme: 'weather', category: 'nature' },
  { word: 'dew', theme: 'weather', category: 'nature' },
  { word: 'frost', theme: 'weather', category: 'nature' },
  { word: 'snow', theme: 'weather', category: 'nature' },
  { word: 'rain', theme: 'weather', category: 'nature' },
  { word: 'sleet', theme: 'weather', category: 'nature' },
  { word: 'hail', theme: 'weather', category: 'nature' },
  { word: 'wind', theme: 'weather', category: 'nature' },
  { word: 'breeze', theme: 'weather', category: 'nature' },
  { word: 'gale', theme: 'weather', category: 'nature' },
  { word: 'cloud', theme: 'weather', category: 'nature' },
  { word: 'sunrise', theme: 'time', category: 'nature' },
  { word: 'sunset', theme: 'time', category: 'nature' },
  { word: 'eclipse', theme: 'phenomenon', category: 'nature' },
  { word: 'aurora', theme: 'phenomenon', category: 'nature' },
  { word: 'meteor', theme: 'space', category: 'nature' },
  { word: 'comet', theme: 'space', category: 'nature' },
  { word: 'asteroid', theme: 'space', category: 'nature' },
  { word: 'moon', theme: 'celestial', category: 'nature' },
  { word: 'star', theme: 'celestial', category: 'nature' },
  { word: 'planet', theme: 'celestial', category: 'nature' },
  { word: 'galaxy', theme: 'space', category: 'nature' },
  { word: 'nebula', theme: 'space', category: 'nature' },

  // --- Video Games (150+ words) ---
  { word: 'Minecraft', theme: 'cubic world', category: 'videogames' },
  { word: 'Fortnite', theme: 'building shooter', category: 'videogames' },
  { word: 'Pokemon', theme: 'gotta catch em', category: 'videogames' },
  { word: 'Mario', theme: 'red plumber', category: 'videogames' },
  { word: 'Zelda', theme: 'triforce quest', category: 'videogames' },
  { word: 'Sonic', theme: 'blue speedster', category: 'videogames' },
  { word: 'Tetris', theme: 'block puzzle', category: 'videogames' },
  { word: 'Roblox', theme: 'user games', category: 'videogames' },
  { word: 'Among Us', theme: 'crew betrayal', category: 'videogames' },
  { word: 'Valorant', theme: 'agent shooter', category: 'videogames' },
  { word: 'Overwatch', theme: 'hero team', category: 'videogames' },
  { word: 'League of Legends', theme: 'lane battle', category: 'videogames' },
  { word: 'Dota', theme: 'ancient defense', category: 'videogames' },
  { word: 'Call of Duty', theme: 'modern warfare', category: 'videogames' },
  { word: 'Battlefield', theme: 'large scale war', category: 'videogames' },
  { word: 'GTA', theme: 'city chaos', category: 'videogames' },
  { word: 'Skyrim', theme: 'arrow to knee', category: 'videogames' },
  { word: 'Halo', theme: 'spartan ring', category: 'videogames' },
  { word: 'Apex Legends', theme: 'champion squad', category: 'videogames' },
  { word: 'Rocket League', theme: 'vehicle sports', category: 'videogames' },
  { word: 'Fall Guys', theme: 'bean race', category: 'videogames' },
  { word: 'Stardew Valley', theme: 'farm life', category: 'videogames' },
  { word: 'Animal Crossing', theme: 'island debt', category: 'videogames' },
  { word: 'Sims', theme: 'virtual people', category: 'videogames' },
  { word: 'Undertale', theme: 'mercy or fight', category: 'videogames' },
  { word: 'Hollow Knight', theme: 'void vessel', category: 'videogames' },
  { word: 'Dark Souls', theme: 'you died', category: 'videogames' },
  { word: 'Elden Ring', theme: 'tarnished quest', category: 'videogames' },
  { word: 'Cyberpunk', theme: 'neon future', category: 'videogames' },
  { word: 'Witcher', theme: 'silver sword', category: 'videogames' },
  { word: 'Red Dead Redemption', theme: 'outlaw story', category: 'videogames' },
  { word: 'Assassins Creed', theme: 'hidden blade', category: 'videogames' },
  { word: 'God of War', theme: 'boy father', category: 'videogames' },
  { word: 'Spider-Man', theme: 'web swinging', category: 'videogames' },
  { word: 'Batman Arkham', theme: 'detective mode', category: 'videogames' },
  { word: 'Uncharted', theme: 'climbing ruins', category: 'videogames' },
  { word: 'Last of Us', theme: 'fungal outbreak', category: 'videogames' },
  { word: 'Resident Evil', theme: 'mansion survival', category: 'videogames' },
  { word: 'Silent Hill', theme: 'foggy town', category: 'videogames' },
  { word: 'Dead Space', theme: 'plasma cutter', category: 'videogames' },
  { word: 'Outlast', theme: 'camera battery', category: 'videogames' },
  { word: 'Five Nights at Freddys', theme: 'night shift', category: 'videogames' },
  { word: 'Phasmophobia', theme: 'spirit box', category: 'videogames' },
  { word: 'Portal', theme: 'cake lie', category: 'videogames' },
  { word: 'Half-Life', theme: 'shooter', category: 'videogames' },
  { word: 'Counter-Strike', theme: 'shooter', category: 'videogames' },
  { word: 'Team Fortress', theme: 'shooter', category: 'videogames' },
  { word: 'Left 4 Dead', theme: 'shooter', category: 'videogames' },
  { word: 'Payday', theme: 'shooter', category: 'videogames' },
  { word: 'Destiny', theme: 'shooter', category: 'videogames' },
  { word: 'Borderlands', theme: 'shooter', category: 'videogames' },
  { word: 'Bioshock', theme: 'shooter', category: 'videogames' },
  { word: 'Fallout', theme: 'RPG', category: 'videogames' },
  { word: 'Mass Effect', theme: 'RPG', category: 'videogames' },
  { word: 'Dragon Age', theme: 'RPG', category: 'videogames' },
  { word: 'Final Fantasy', theme: 'RPG', category: 'videogames' },
  { word: 'Kingdom Hearts', theme: 'RPG', category: 'videogames' },
  { word: 'Persona', theme: 'RPG', category: 'videogames' },
  { word: 'Chrono Trigger', theme: 'RPG', category: 'videogames' },
  { word: 'Earthbound', theme: 'RPG', category: 'videogames' },
  { word: 'Metal Gear', theme: 'stealth', category: 'videogames' },
  { word: 'Splinter Cell', theme: 'stealth', category: 'videogames' },
  { word: 'Hitman', theme: 'stealth', category: 'videogames' },
  { word: 'Dishonored', theme: 'stealth', category: 'videogames' },
  { word: 'Thief', theme: 'stealth', category: 'videogames' },
  { word: 'Deus Ex', theme: 'RPG', category: 'videogames' },
  { word: 'System Shock', theme: 'shooter', category: 'videogames' },
  { word: 'Prey', theme: 'shooter', category: 'videogames' },
  { word: 'Doom', theme: 'shooter', category: 'videogames' },
  { word: 'Quake', theme: 'shooter', category: 'videogames' },
  { word: 'Wolfenstein', theme: 'shooter', category: 'videogames' },
  { word: 'Metroid', theme: 'metroidvania', category: 'videogames' },
  { word: 'Castlevania', theme: 'metroidvania', category: 'videogames' },
  { word: 'Mega Man', theme: 'platformer', category: 'videogames' },
  { word: 'Kirby', theme: 'platformer', category: 'videogames' },
  { word: 'Donkey Kong', theme: 'platformer', category: 'videogames' },
  { word: 'Crash Bandicoot', theme: 'platformer', category: 'videogames' },
  { word: 'Spyro', theme: 'platformer', category: 'videogames' },
  { word: 'Ratchet and Clank', theme: 'platformer', category: 'videogames' },
  { word: 'Jak and Daxter', theme: 'platformer', category: 'videogames' },
  { word: 'Sly Cooper', theme: 'platformer', category: 'videogames' },
  { word: 'Rayman', theme: 'platformer', category: 'videogames' },
  { word: 'Banjo-Kazooie', theme: 'platformer', category: 'videogames' },
  { word: 'Yoshi', theme: 'platformer', category: 'videogames' },
  { word: 'Luigi', theme: 'platformer', category: 'videogames' },
  { word: 'Wario', theme: 'platformer', category: 'videogames' },
  { word: 'Pac-Man', theme: 'arcade', category: 'videogames' },
  { word: 'Space Invaders', theme: 'arcade', category: 'videogames' },
  { word: 'Galaga', theme: 'arcade', category: 'videogames' },
  { word: 'Asteroids', theme: 'arcade', category: 'videogames' },
  { word: 'Pong', theme: 'arcade', category: 'videogames' },
  { word: 'Street Fighter', theme: 'fighting', category: 'videogames' },
  { word: 'Mortal Kombat', theme: 'fighting', category: 'videogames' },
  { word: 'Tekken', theme: 'fighting', category: 'videogames' },
  { word: 'Smash Bros', theme: 'fighting', category: 'videogames' },
  { word: 'Guilty Gear', theme: 'fighting', category: 'videogames' },
  { word: 'BlazBlue', theme: 'fighting', category: 'videogames' },
  { word: 'Dragon Ball FighterZ', theme: 'fighting', category: 'videogames' },
  { word: 'Naruto', theme: 'fighting', category: 'videogames' },
  { word: 'One Piece', theme: 'fighting', category: 'videogames' },
  { word: 'FIFA', theme: 'sports', category: 'videogames' },
  { word: 'Madden', theme: 'sports', category: 'videogames' },
  { word: 'NBA 2K', theme: 'sports', category: 'videogames' },
  { word: 'MLB The Show', theme: 'sports', category: 'videogames' },
  { word: 'NHL', theme: 'sports', category: 'videogames' },
  { word: 'Tony Hawk', theme: 'sports', category: 'videogames' },
  { word: 'Skate', theme: 'sports', category: 'videogames' },
  { word: 'Gran Turismo', theme: 'racing', category: 'videogames' },
  { word: 'Forza', theme: 'racing', category: 'videogames' },
  { word: 'Need for Speed', theme: 'racing', category: 'videogames' },
  { word: 'Mario Kart', theme: 'racing', category: 'videogames' },
  { word: 'Burnout', theme: 'racing', category: 'videogames' },
  { word: 'F-Zero', theme: 'racing', category: 'videogames' },
  { word: 'Wipeout', theme: 'racing', category: 'videogames' },
  { word: 'Civilization', theme: 'strategy', category: 'videogames' },
  { word: 'Age of Empires', theme: 'strategy', category: 'videogames' },
  { word: 'StarCraft', theme: 'strategy', category: 'videogames' },
  { word: 'Warcraft', theme: 'strategy', category: 'videogames' },
  { word: 'Command and Conquer', theme: 'strategy', category: 'videogames' },
  { word: 'Total War', theme: 'strategy', category: 'videogames' },
  { word: 'XCOM', theme: 'strategy', category: 'videogames' },
  { word: 'Fire Emblem', theme: 'strategy', category: 'videogames' },
  { word: 'Advance Wars', theme: 'strategy', category: 'videogames' },
  { word: 'Chess', theme: 'board', category: 'videogames' },
  { word: 'Hearthstone', theme: 'card', category: 'videogames' },
  { word: 'Magic The Gathering', theme: 'card', category: 'videogames' },
  { word: 'Yu-Gi-Oh', theme: 'card', category: 'videogames' },
  { word: 'Solitaire', theme: 'card', category: 'videogames' },
  { word: 'Minesweeper', theme: 'puzzle', category: 'videogames' },
  { word: 'Sudoku', theme: 'puzzle', category: 'videogames' },
  { word: 'Candy Crush', theme: 'puzzle', category: 'videogames' },
  { word: 'Bejeweled', theme: 'puzzle', category: 'videogames' },
  { word: 'Angry Birds', theme: 'puzzle', category: 'videogames' },
  { word: 'Cut the Rope', theme: 'puzzle', category: 'videogames' },
  { word: 'Plants vs Zombies', theme: 'tower defense', category: 'videogames' },
  { word: 'Bloons', theme: 'tower defense', category: 'videogames' },
  { word: 'Terraria', theme: 'sandbox', category: 'videogames' },
  { word: 'Starbound', theme: 'sandbox', category: 'videogames' },
  { word: 'Rust', theme: 'survival', category: 'videogames' },
  { word: 'ARK', theme: 'survival', category: 'videogames' },
  { word: 'Subnautica', theme: 'survival', category: 'videogames' },
  { word: 'The Forest', theme: 'survival', category: 'videogames' },
  { word: 'Dont Starve', theme: 'survival', category: 'videogames' },
  { word: 'Valheim', theme: 'survival', category: 'videogames' },
  { word: 'Satisfactory', theme: 'simulation', category: 'videogames' },
  { word: 'Factorio', theme: 'simulation', category: 'videogames' },
  { word: 'Rimworld', theme: 'simulation', category: 'videogames' },
  { word: 'Dwarf Fortress', theme: 'simulation', category: 'videogames' },
  { word: 'Cities Skylines', theme: 'simulation', category: 'videogames' },
  { word: 'SimCity', theme: 'simulation', category: 'videogames' },
  { word: 'Roller Coaster Tycoon', theme: 'simulation', category: 'videogames' },
  { word: 'Planet Coaster', theme: 'simulation', category: 'videogames' },
  { word: 'Zoo Tycoon', theme: 'simulation', category: 'videogames' },
  { word: 'Flight Simulator', theme: 'simulation', category: 'videogames' },
  { word: 'Euro Truck Simulator', theme: 'simulation', category: 'videogames' },
  { word: 'Farming Simulator', theme: 'simulation', category: 'videogames' },

  // --- Music Artists (100+ words) ---
  { word: 'Taylor Swift', theme: 'shake it off', category: 'music' },
  { word: 'Drake', theme: 'started from bottom', category: 'music' },
  { word: 'Beyonce', theme: 'single ladies', category: 'music' },
  { word: 'The Weeknd', theme: 'blinding lights', category: 'music' },
  { word: 'Billie Eilish', theme: 'bad guy', category: 'music' },
  { word: 'Ed Sheeran', theme: 'shape of you', category: 'music' },
  { word: 'Ariana Grande', theme: 'thank u next', category: 'music' },
  { word: 'Post Malone', theme: 'face tattoos', category: 'music' },
  { word: 'Dua Lipa', theme: 'levitating', category: 'music' },
  { word: 'Bad Bunny', theme: 'Latin trap', category: 'music' },
  { word: 'BTS', theme: 'Korean wave', category: 'music' },
  { word: 'Olivia Rodrigo', theme: 'drivers license', category: 'music' },
  { word: 'Harry Styles', theme: 'watermelon sugar', category: 'music' },
  { word: 'Doja Cat', theme: 'say so', category: 'music' },
  { word: 'Travis Scott', theme: 'sicko mode', category: 'music' },
  { word: 'Kanye West', theme: 'yeezus', category: 'music' },
  { word: 'Eminem', theme: 'rap god', category: 'music' },
  { word: 'Rihanna', theme: 'umbrella ella', category: 'music' },
  { word: 'Lady Gaga', theme: 'poker face', category: 'music' },
  { word: 'Bruno Mars', theme: 'uptown funk', category: 'music' },
  { word: 'Adele', theme: 'rolling deep', category: 'music' },
  { word: 'Coldplay', theme: 'yellow star', category: 'music' },
  { word: 'Imagine Dragons', theme: 'radioactive', category: 'music' },
  { word: 'Twenty One Pilots', theme: 'stressed out', category: 'music' },
  { word: 'Maroon 5', theme: 'moves like', category: 'music' },
  { word: 'OneRepublic', theme: 'band', category: 'music' },
  { word: 'The Chainsmokers', theme: 'duo', category: 'music' },
  { word: 'Marshmello', theme: 'artist', category: 'music' },
  { word: 'Calvin Harris', theme: 'artist', category: 'music' },
  { word: 'David Guetta', theme: 'artist', category: 'music' },
  { word: 'Avicii', theme: 'artist', category: 'music' },
  { word: 'Skrillex', theme: 'artist', category: 'music' },
  { word: 'Deadmau5', theme: 'artist', category: 'music' },
  { word: 'Diplo', theme: 'artist', category: 'music' },
  { word: 'Zedd', theme: 'artist', category: 'music' },
  { word: 'Tiesto', theme: 'artist', category: 'music' },
  { word: 'Martin Garrix', theme: 'artist', category: 'music' },
  { word: 'Kygo', theme: 'artist', category: 'music' },
  { word: 'Alan Walker', theme: 'artist', category: 'music' },
  { word: 'Daft Punk', theme: 'duo', category: 'music' },
  { word: 'Justice', theme: 'duo', category: 'music' },
  { word: 'Disclosure', theme: 'duo', category: 'music' },
  { word: 'ODESZA', theme: 'duo', category: 'music' },
  { word: 'Flume', theme: 'artist', category: 'music' },
  { word: 'Porter Robinson', theme: 'artist', category: 'music' },
  { word: 'Madeon', theme: 'artist', category: 'music' },
  { word: 'Illenium', theme: 'artist', category: 'music' },
  { word: 'Seven Lions', theme: 'artist', category: 'music' },
  { word: 'Excision', theme: 'artist', category: 'music' },
  { word: 'Bassnectar', theme: 'artist', category: 'music' },
  { word: 'Kendrick Lamar', theme: 'artist', category: 'music' },
  { word: 'J Cole', theme: 'artist', category: 'music' },
  { word: 'Lil Wayne', theme: 'artist', category: 'music' },
  { word: 'Nicki Minaj', theme: 'artist', category: 'music' },
  { word: 'Cardi B', theme: 'artist', category: 'music' },
  { word: 'Megan Thee Stallion', theme: 'artist', category: 'music' },
  { word: 'Lil Nas X', theme: 'artist', category: 'music' },
  { word: 'Tyler The Creator', theme: 'artist', category: 'music' },
  { word: 'Frank Ocean', theme: 'artist', category: 'music' },
  { word: 'The Weeknd', theme: 'artist', category: 'music' },
  { word: 'SZA', theme: 'artist', category: 'music' },
  { word: 'H.E.R.', theme: 'artist', category: 'music' },
  { word: 'Khalid', theme: 'artist', category: 'music' },
  { word: 'Shawn Mendes', theme: 'artist', category: 'music' },
  { word: 'Justin Bieber', theme: 'artist', category: 'music' },
  { word: 'Selena Gomez', theme: 'artist', category: 'music' },
  { word: 'Demi Lovato', theme: 'artist', category: 'music' },
  { word: 'Miley Cyrus', theme: 'artist', category: 'music' },
  { word: 'Katy Perry', theme: 'artist', category: 'music' },
  { word: 'Britney Spears', theme: 'artist', category: 'music' },
  { word: 'Christina Aguilera', theme: 'artist', category: 'music' },
  { word: 'Pink', theme: 'artist', category: 'music' },
  { word: 'Shakira', theme: 'artist', category: 'music' },
  { word: 'Jennifer Lopez', theme: 'artist', category: 'music' },
  { word: 'Madonna', theme: 'artist', category: 'music' },
  { word: 'Cher', theme: 'artist', category: 'music' },
  { word: 'Elton John', theme: 'artist', category: 'music' },
  { word: 'Billy Joel', theme: 'artist', category: 'music' },
  { word: 'Stevie Wonder', theme: 'artist', category: 'music' },
  { word: 'Prince', theme: 'artist', category: 'music' },
  { word: 'Michael Jackson', theme: 'artist', category: 'music' },
  { word: 'Whitney Houston', theme: 'artist', category: 'music' },
  { word: 'Mariah Carey', theme: 'artist', category: 'music' },
  { word: 'Celine Dion', theme: 'artist', category: 'music' },
  { word: 'The Beatles', theme: 'band', category: 'music' },
  { word: 'The Rolling Stones', theme: 'band', category: 'music' },
  { word: 'Led Zeppelin', theme: 'band', category: 'music' },
  { word: 'Pink Floyd', theme: 'band', category: 'music' },
  { word: 'Queen', theme: 'band', category: 'music' },
  { word: 'AC/DC', theme: 'band', category: 'music' },
  { word: 'Metallica', theme: 'band', category: 'music' },
  { word: 'Nirvana', theme: 'band', category: 'music' },
  { word: 'Foo Fighters', theme: 'band', category: 'music' },
  { word: 'Green Day', theme: 'band', category: 'music' },
  { word: 'Blink-182', theme: 'band', category: 'music' },
  { word: 'Linkin Park', theme: 'band', category: 'music' },
  { word: 'Red Hot Chili Peppers', theme: 'band', category: 'music' },
  { word: 'Radiohead', theme: 'band', category: 'music' },
  { word: 'Muse', theme: 'band', category: 'music' },
  { word: 'Arctic Monkeys', theme: 'band', category: 'music' },
  { word: 'The Strokes', theme: 'band', category: 'music' },
  { word: 'The Killers', theme: 'band', category: 'music' },
  { word: 'Fall Out Boy', theme: 'band', category: 'music' },
  { word: 'Panic at the Disco', theme: 'band', category: 'music' },
  { word: 'My Chemical Romance', theme: 'band', category: 'music' },
  { word: 'Paramore', theme: 'band', category: 'music' },
  { word: 'Evanescence', theme: 'band', category: 'music' },
  { word: 'Fleetwood Mac', theme: 'band', category: 'music' },
  { word: 'Eagles', theme: 'band', category: 'music' },
  { word: 'Journey', theme: 'band', category: 'music' },
  { word: 'Boston', theme: 'band', category: 'music' },
  { word: 'Toto', theme: 'band', category: 'music' },
  { word: 'U2', theme: 'band', category: 'music' },
  { word: 'R.E.M.', theme: 'band', category: 'music' },
  { word: 'Oasis', theme: 'band', category: 'music' },
  { word: 'Blur', theme: 'band', category: 'music' },
  { word: 'The Smiths', theme: 'band', category: 'music' },
  { word: 'Joy Division', theme: 'band', category: 'music' },
  { word: 'New Order', theme: 'band', category: 'music' },
  { word: 'Depeche Mode', theme: 'band', category: 'music' },
  { word: 'The Cure', theme: 'band', category: 'music' },
  { word: 'Duran Duran', theme: 'band', category: 'music' },

  // --- Memes & Internet Culture (80+ words) ---
  { word: 'Skibidi Toilet', theme: 'brainrot', category: 'memes' },
  { word: 'Rizz', theme: 'brainrot', category: 'memes' },
  { word: 'Sigma Male', theme: 'brainrot', category: 'memes' },
  { word: 'Gyat', theme: 'brainrot', category: 'memes' },
  { word: 'Ohio', theme: 'brainrot', category: 'memes' },
  { word: 'Fanum Tax', theme: 'brainrot', category: 'memes' },
  { word: 'Grimace Shake', theme: 'brainrot', category: 'memes' },
  { word: 'Giga Chad', theme: 'brainrot', category: 'memes' },
  { word: 'Sigma Face', theme: 'brainrot', category: 'memes' },
  { word: 'Mewing', theme: 'brainrot', category: 'memes' },
  { word: 'Looksmaxxing', theme: 'brainrot', category: 'memes' },
  { word: 'Mogging', theme: 'brainrot', category: 'memes' },
  { word: 'Aura Points', theme: 'brainrot', category: 'memes' },
  { word: 'NPC', theme: 'brainrot', category: 'memes' },
  { word: 'Main Character', theme: 'brainrot', category: 'memes' },
  { word: 'Its Giving', theme: 'slang', category: 'memes' },
  { word: 'Slay', theme: 'slang', category: 'memes' },
  { word: 'No Cap', theme: 'slang', category: 'memes' },
  { word: 'Bussin', theme: 'slang', category: 'memes' },
  { word: 'Sheesh', theme: 'slang', category: 'memes' },
  { word: 'Caught in 4K', theme: 'slang', category: 'memes' },
  { word: 'Ratio', theme: 'slang', category: 'memes' },
  { word: 'Touch Grass', theme: 'slang', category: 'memes' },
  { word: 'Chronically Online', theme: 'slang', category: 'memes' },
  { word: 'Unhinged', theme: 'slang', category: 'memes' },
  { word: 'Delulu', theme: 'slang', category: 'memes' },
  { word: 'Snatched', theme: 'slang', category: 'memes' },
  { word: 'Periodt', theme: 'slang', category: 'memes' },
  { word: 'Ick', theme: 'slang', category: 'memes' },
  { word: 'Red Flag', theme: 'slang', category: 'memes' },
  { word: 'Green Flag', theme: 'slang', category: 'memes' },
  { word: 'Beige Flag', theme: 'slang', category: 'memes' },
  { word: 'Vibe Check', theme: 'slang', category: 'memes' },
  { word: 'POV', theme: 'slang', category: 'memes' },
  { word: 'This You', theme: 'slang', category: 'memes' },
  { word: 'Main Character Syndrome', theme: 'slang', category: 'memes' },
  { word: 'Rent Free', theme: 'slang', category: 'memes' },
  { word: 'Its the For Me', theme: 'slang', category: 'memes' },
  { word: 'Not the', theme: 'slang', category: 'memes' },
  { word: 'Chefs Kiss', theme: 'slang', category: 'memes' },
  { word: 'Hits Different', theme: 'slang', category: 'memes' },
  { word: 'Down Bad', theme: 'slang', category: 'memes' },
  { word: 'Simp', theme: 'slang', category: 'memes' },
  { word: 'Stan', theme: 'slang', category: 'memes' },
  { word: 'Oomf', theme: 'slang', category: 'memes' },
  { word: 'Moots', theme: 'slang', category: 'memes' },
  { word: 'Bestie', theme: 'slang', category: 'memes' },
  { word: 'Bffr', theme: 'slang', category: 'memes' },
  { word: 'Iykyk', theme: 'slang', category: 'memes' },
  { word: 'Hear Me Out', theme: 'slang', category: 'memes' },
  { word: 'Roman Empire', theme: 'slang', category: 'memes' },
  { word: 'Girl Math', theme: 'slang', category: 'memes' },
  { word: 'Boy Math', theme: 'slang', category: 'memes' },
  { word: 'Girl Dinner', theme: 'slang', category: 'memes' },
  { word: 'Hot Girl Walk', theme: 'slang', category: 'memes' },
  { word: 'Bed Rotting', theme: 'slang', category: 'memes' },
  { word: 'Doom Scrolling', theme: 'slang', category: 'memes' },
  { word: 'Brain Rot', theme: 'slang', category: 'memes' },
  { word: 'Core Memory', theme: 'slang', category: 'memes' },
  { word: 'Intrusive Thoughts', theme: 'slang', category: 'memes' },
  { word: 'Let Him Cook', theme: 'slang', category: 'memes' },
  { word: 'We Are So Back', theme: 'slang', category: 'memes' },
  { word: 'Its Over', theme: 'slang', category: 'memes' },
  { word: 'Cooked', theme: 'slang', category: 'memes' },
  { word: 'Locked In', theme: 'slang', category: 'memes' },
  { word: 'Goofy Ahh', theme: 'slang', category: 'memes' },
  { word: 'Nah Id Win', theme: 'slang', category: 'memes' },
  { word: 'Lobotomy Kaisen', theme: 'slang', category: 'memes' },
  { word: 'Gooning', theme: 'slang', category: 'memes' },
  { word: 'Edging', theme: 'slang', category: 'memes' },
  { word: 'Goated', theme: 'slang', category: 'memes' },
  { word: 'Mid', theme: 'slang', category: 'memes' },
  { word: 'Peak Fiction', theme: 'slang', category: 'memes' },
  { word: 'Kino', theme: 'slang', category: 'memes' },
  { word: 'Rage Comic', theme: 'meme', category: 'memes' },
  { word: 'Forever Alone', theme: 'meme', category: 'memes' },
  { word: 'Yao Ming', theme: 'meme', category: 'memes' },
  { word: 'Kobe Bryant', theme: 'meme', category: 'memes' },
  { word: 'Buzz Lightyear', theme: 'meme', category: 'memes' },
  { word: 'Mr Incredible', theme: 'meme', category: 'memes' },
  { word: 'Megamind', theme: 'meme', category: 'memes' },
  { word: 'Gru', theme: 'meme', category: 'memes' },
  { word: 'Minions', theme: 'meme', category: 'memes' },
  { word: 'Thanos', theme: 'meme', category: 'memes' },
  { word: 'Smurf Cat', theme: 'brainrot', category: 'memes' },
  { word: 'Quandale Dingle', theme: 'brainrot', category: 'memes' },
  { word: 'Goofy Ahh Uncle', theme: 'brainrot', category: 'memes' },
  { word: 'Huggy Wuggy', theme: 'brainrot', category: 'memes' },
  { word: 'Poppy Playtime', theme: 'brainrot', category: 'memes' },
  { word: 'Backrooms', theme: 'brainrot', category: 'memes' },
  { word: 'Liminal Space', theme: 'brainrot', category: 'memes' },
  { word: 'Uncanny Valley', theme: 'brainrot', category: 'memes' },
  { word: 'Mandela Catalogue', theme: 'brainrot', category: 'memes' },
  { word: 'Analog Horror', theme: 'brainrot', category: 'memes' },
  { word: 'Siren Head', theme: 'brainrot', category: 'memes' },
  { word: 'SCP Foundation', theme: 'brainrot', category: 'memes' },
  { word: 'Creepypasta', theme: 'brainrot', category: 'memes' },
  { word: 'Slenderman', theme: 'brainrot', category: 'memes' },
  { word: 'Jeff The Killer', theme: 'brainrot', category: 'memes' },
  { word: 'Sonic EXE', theme: 'brainrot', category: 'memes' },
  { word: 'Freddy Fazbear', theme: 'brainrot', category: 'memes' },
  { word: 'Among Us Drip', theme: 'brainrot', category: 'memes' },
  { word: 'Big Floppa', theme: 'brainrot', category: 'memes' },
  { word: 'Bingus', theme: 'brainrot', category: 'memes' },
  { word: 'Walter Dog', theme: 'brainrot', category: 'memes' },
  { word: 'Cheems', theme: 'brainrot', category: 'memes' },
  { word: 'Doge', theme: 'brainrot', category: 'memes' },
  { word: 'Shiba Inu', theme: 'brainrot', category: 'memes' },
  { word: 'Chipi Chipi Chapa Chapa', theme: 'brainrot', category: 'memes' },
  { word: 'Gegagedigedagedago', theme: 'brainrot', category: 'memes' },
  { word: 'Phonk Music', theme: 'brainrot', category: 'memes' },
  { word: 'Sigma Grindset', theme: 'brainrot', category: 'memes' },
  { word: 'Alpha Male', theme: 'brainrot', category: 'memes' },
  { word: 'Beta Male', theme: 'brainrot', category: 'memes' },
  { word: 'Omega Male', theme: 'brainrot', category: 'memes' },
  { word: 'Ligma', theme: 'brainrot', category: 'memes' },
  { word: 'Sugma', theme: 'brainrot', category: 'memes' },
  { word: 'Candice', theme: 'brainrot', category: 'memes' },
  { word: 'Joe Mama', theme: 'brainrot', category: 'memes' },
  { word: 'Deez Nuts', theme: 'brainrot', category: 'memes' },
  { word: 'Bofa', theme: 'brainrot', category: 'memes' },
  { word: 'Updog', theme: 'brainrot', category: 'memes' },
  { word: 'Wenomechainsama', theme: 'brainrot', category: 'memes' },
  { word: 'Bing Chilling', theme: 'brainrot', category: 'memes' },
  { word: 'Social Credit', theme: 'brainrot', category: 'memes' },
  { word: 'Zhong Xina', theme: 'brainrot', category: 'memes' },
  { word: 'Wok', theme: 'brainrot', category: 'memes' },
  { word: 'Bing Bong', theme: 'brainrot', category: 'memes' },
  { word: 'Glizzy', theme: 'brainrot', category: 'memes' },
  { word: 'Glizzy Gobbler', theme: 'brainrot', category: 'memes' },
  { word: 'Zesty', theme: 'brainrot', category: 'memes' },
  { word: 'Sassy', theme: 'brainrot', category: 'memes' },
  { word: 'Material Girl', theme: 'brainrot', category: 'memes' },
  { word: 'Girlboss', theme: 'brainrot', category: 'memes' },
  { word: 'Gaslight', theme: 'brainrot', category: 'memes' },
  { word: 'Gatekeep', theme: 'brainrot', category: 'memes' },
  { word: 'Slay Queen', theme: 'brainrot', category: 'memes' },
  { word: 'Yassify', theme: 'brainrot', category: 'memes' },
  { word: 'Serving', theme: 'brainrot', category: 'memes' },
  { word: 'Ate And Left No Crumbs', theme: 'brainrot', category: 'memes' },
  { word: 'Understood The Assignment', theme: 'brainrot', category: 'memes' },
  { word: 'Living For This', theme: 'brainrot', category: 'memes' },
  { word: 'Obsessed', theme: 'brainrot', category: 'memes' },
  { word: 'Unalive', theme: 'brainrot', category: 'memes' },
  { word: 'Seggs', theme: 'brainrot', category: 'memes' },
  { word: 'Le Dollar Bean', theme: 'brainrot', category: 'memes' },
  { word: 'Corn', theme: 'brainrot', category: 'memes' },
  { word: 'Accountant', theme: 'brainrot', category: 'memes' },
  { word: 'Cheugy', theme: 'brainrot', category: 'memes' },
  { word: 'Bussin No Cap', theme: 'brainrot', category: 'memes' },
  { word: 'Respectfully', theme: 'brainrot', category: 'memes' },
  { word: 'Disrespectfully', theme: 'brainrot', category: 'memes' },
  { word: 'Purr', theme: 'brainrot', category: 'memes' },
  { word: 'Slay Boots', theme: 'brainrot', category: 'memes' },
  { word: 'Boots The House Down', theme: 'brainrot', category: 'memes' },
  { word: 'Cunty', theme: 'brainrot', category: 'memes' },
  { word: 'Demure', theme: 'brainrot', category: 'memes' },
  { word: 'Very Mindful', theme: 'brainrot', category: 'memes' },
  { word: 'Very Cutesy', theme: 'brainrot', category: 'memes' },
  { word: 'Brat Summer', theme: 'brainrot', category: 'memes' },
  { word: 'Tomato Girl', theme: 'brainrot', category: 'memes' },
  { word: 'Clean Girl', theme: 'brainrot', category: 'memes' },
  { word: 'That Girl', theme: 'brainrot', category: 'memes' },
  { word: 'Coquette', theme: 'brainrot', category: 'memes' },
  { word: 'Cottage Core', theme: 'brainrot', category: 'memes' },
  { word: 'Dark Academia', theme: 'brainrot', category: 'memes' },
  { word: 'Light Academia', theme: 'brainrot', category: 'memes' },
  { word: 'Goblin Mode', theme: 'brainrot', category: 'memes' },
  { word: 'Feral', theme: 'brainrot', category: 'memes' },
  { word: 'Unhinged Era', theme: 'brainrot', category: 'memes' },
  { word: 'Villain Era', theme: 'brainrot', category: 'memes' },
  { word: 'Healing Era', theme: 'brainrot', category: 'memes' },
  { word: 'Soft Launch', theme: 'brainrot', category: 'memes' },
  { word: 'Hard Launch', theme: 'brainrot', category: 'memes' },
  { word: 'Situationship', theme: 'brainrot', category: 'memes' },
  { word: 'Talking Stage', theme: 'brainrot', category: 'memes' },
  { word: 'Breadcrumbing', theme: 'brainrot', category: 'memes' },
  { word: 'Ghosting', theme: 'brainrot', category: 'memes' },
  { word: 'Orbiting', theme: 'brainrot', category: 'memes' },
  { word: 'Benching', theme: 'brainrot', category: 'memes' },
  { word: 'Zombieing', theme: 'brainrot', category: 'memes' },
  { word: 'Cuffing Season', theme: 'brainrot', category: 'memes' },
  { word: 'Ick List', theme: 'brainrot', category: 'memes' },
  { word: 'Beige Flag Energy', theme: 'brainrot', category: 'memes' },

  // --- Movies & TV (100+ words) ---
  { word: 'Star Wars', theme: 'may the force', category: 'movies' },
  { word: 'Harry Potter', theme: 'boy who lived', category: 'movies' },
  { word: 'Marvel', theme: 'cinematic universe', category: 'movies' },
  { word: 'Lord of the Rings', theme: 'one ring', category: 'movies' },
  { word: 'Titanic', theme: 'iceberg romance', category: 'movies' },
  { word: 'Avatar', theme: 'Pandora Navi', category: 'movies' },
  { word: 'Jurassic Park', theme: 'life finds way', category: 'movies' },
  { word: 'The Matrix', theme: 'red blue pill', category: 'movies' },
  { word: 'Inception', theme: 'dream layers', category: 'movies' },
  { word: 'Frozen', theme: 'let it go', category: 'movies' },
  { word: 'Toy Story', theme: 'to infinity', category: 'movies' },
  { word: 'Shrek', theme: 'swamp donkey', category: 'movies' },
  { word: 'Breaking Bad', theme: 'say my name', category: 'movies' },
  { word: 'Game of Thrones', theme: 'winter coming', category: 'movies' },
  { word: 'Stranger Things', theme: 'upside down', category: 'movies' },
  { word: 'The Office', theme: 'thats what she', category: 'movies' },
  { word: 'Friends', theme: 'central perk', category: 'movies' },
  { word: 'Spongebob', theme: 'ready ready', category: 'movies' },
  { word: 'Rick and Morty', theme: 'wubba lubba', category: 'movies' },
  { word: 'Squid Game', theme: 'red light green', category: 'movies' },
  { word: 'The Simpsons', theme: 'show', category: 'movies' },
  { word: 'Family Guy', theme: 'show', category: 'movies' },
  { word: 'South Park', theme: 'show', category: 'movies' },
  { word: 'Futurama', theme: 'show', category: 'movies' },
  { word: 'Adventure Time', theme: 'show', category: 'movies' },
  { word: 'Regular Show', theme: 'show', category: 'movies' },
  { word: 'Gravity Falls', theme: 'show', category: 'movies' },
  { word: 'Steven Universe', theme: 'show', category: 'movies' },
  { word: 'Avatar The Last Airbender', theme: 'show', category: 'movies' },
  { word: 'Legend of Korra', theme: 'show', category: 'movies' },
  { word: 'Teen Titans', theme: 'show', category: 'movies' },
  { word: 'Ben 10', theme: 'show', category: 'movies' },
  { word: 'Danny Phantom', theme: 'show', category: 'movies' },
  { word: 'Kim Possible', theme: 'show', category: 'movies' },
  { word: 'Phineas and Ferb', theme: 'show', category: 'movies' },
  { word: 'Fairly OddParents', theme: 'show', category: 'movies' },
  { word: 'Jimmy Neutron', theme: 'show', category: 'movies' },
  { word: 'Rugrats', theme: 'show', category: 'movies' },
  { word: 'Hey Arnold', theme: 'show', category: 'movies' },
  { word: 'Courage the Cowardly Dog', theme: 'show', category: 'movies' },
  { word: 'Ed Edd n Eddy', theme: 'show', category: 'movies' },
  { word: 'Dexter Laboratory', theme: 'show', category: 'movies' },
  { word: 'Powerpuff Girls', theme: 'show', category: 'movies' },
  { word: 'Samurai Jack', theme: 'show', category: 'movies' },
  { word: 'Johnny Bravo', theme: 'show', category: 'movies' },
  { word: 'Scooby-Doo', theme: 'show', category: 'movies' },
  { word: 'Tom and Jerry', theme: 'show', category: 'movies' },
  { word: 'Looney Tunes', theme: 'show', category: 'movies' },
  { word: 'Batman', theme: 'franchise', category: 'movies' },
  { word: 'Superman', theme: 'franchise', category: 'movies' },
  { word: 'Spider-Man', theme: 'franchise', category: 'movies' },
  { word: 'Iron Man', theme: 'character', category: 'movies' },
  { word: 'Captain America', theme: 'character', category: 'movies' },
  { word: 'Thor', theme: 'character', category: 'movies' },
  { word: 'Hulk', theme: 'character', category: 'movies' },
  { word: 'Black Widow', theme: 'character', category: 'movies' },
  { word: 'Avengers', theme: 'franchise', category: 'movies' },
  { word: 'X-Men', theme: 'franchise', category: 'movies' },
  { word: 'Deadpool', theme: 'character', category: 'movies' },
  { word: 'Wolverine', theme: 'character', category: 'movies' },
  { word: 'Guardians of the Galaxy', theme: 'franchise', category: 'movies' },
  { word: 'Black Panther', theme: 'character', category: 'movies' },
  { word: 'Doctor Strange', theme: 'character', category: 'movies' },
  { word: 'Ant-Man', theme: 'character', category: 'movies' },
  { word: 'The Mandalorian', theme: 'show', category: 'movies' },
  { word: 'Baby Yoda', theme: 'character', category: 'movies' },
  { word: 'Darth Vader', theme: 'character', category: 'movies' },
  { word: 'Luke Skywalker', theme: 'character', category: 'movies' },
  { word: 'Princess Leia', theme: 'character', category: 'movies' },
  { word: 'Han Solo', theme: 'character', category: 'movies' },
  { word: 'Chewbacca', theme: 'character', category: 'movies' },
  { word: 'Yoda', theme: 'character', category: 'movies' },
  { word: 'Obi-Wan Kenobi', theme: 'character', category: 'movies' },
  { word: 'Anakin Skywalker', theme: 'character', category: 'movies' },
  { word: 'Padme', theme: 'character', category: 'movies' },
  { word: 'Rey', theme: 'character', category: 'movies' },
  { word: 'Kylo Ren', theme: 'character', category: 'movies' },
  { word: 'The Hobbit', theme: 'franchise', category: 'movies' },
  { word: 'Frodo', theme: 'character', category: 'movies' },
  { word: 'Gandalf', theme: 'character', category: 'movies' },
  { word: 'Aragorn', theme: 'character', category: 'movies' },
  { word: 'Legolas', theme: 'character', category: 'movies' },
  { word: 'Gimli', theme: 'character', category: 'movies' },
  { word: 'Gollum', theme: 'character', category: 'movies' },
  { word: 'Sauron', theme: 'character', category: 'movies' },
  { word: 'Dumbledore', theme: 'character', category: 'movies' },
  { word: 'Voldemort', theme: 'character', category: 'movies' },
  { word: 'Hermione', theme: 'character', category: 'movies' },
  { word: 'Ron Weasley', theme: 'character', category: 'movies' },
  { word: 'Snape', theme: 'character', category: 'movies' },
  { word: 'Hagrid', theme: 'character', category: 'movies' },
  { word: 'Dobby', theme: 'character', category: 'movies' },
  { word: 'Draco Malfoy', theme: 'character', category: 'movies' },
  { word: 'The Walking Dead', theme: 'show', category: 'movies' },
  { word: 'Lost', theme: 'show', category: 'movies' },
  { word: 'Prison Break', theme: 'show', category: 'movies' },
  { word: 'Dexter', theme: 'show', category: 'movies' },
  { word: 'House', theme: 'show', category: 'movies' },
  { word: 'Sherlock', theme: 'show', category: 'movies' },
  { word: 'Doctor Who', theme: 'show', category: 'movies' },
  // --- Technology & Objects (80+ words) ---
  { word: 'iPhone', theme: 'device', category: 'technology' },
  { word: 'laptop', theme: 'device', category: 'technology' },
  { word: 'robot', theme: 'machine', category: 'technology' },
  { word: 'smartphone', theme: 'device', category: 'technology' },
  { word: 'headphones', theme: 'device', category: 'technology' },
  { word: 'drone', theme: 'device', category: 'technology' },
  { word: 'keyboard', theme: 'device', category: 'technology' },
  { word: 'mouse', theme: 'device', category: 'technology' },
  { word: 'monitor', theme: 'device', category: 'technology' },
  { word: 'television', theme: 'device', category: 'technology' },
  { word: 'camera', theme: 'device', category: 'technology' },
  { word: 'Tesla', theme: 'brand', category: 'technology' },
  { word: 'WiFi', theme: 'technology', category: 'technology' },
  { word: 'Bluetooth', theme: 'technology', category: 'technology' },
  { word: 'USB', theme: 'technology', category: 'technology' },
  { word: 'VR headset', theme: 'device', category: 'technology' },
  { word: 'smartwatch', theme: 'device', category: 'technology' },
  { word: 'tablet', theme: 'device', category: 'technology' },
  { word: 'speaker', theme: 'device', category: 'technology' },
  { word: 'microphone', theme: 'device', category: 'technology' },
  { word: 'webcam', theme: 'device', category: 'technology' },
  { word: 'printer', theme: 'device', category: 'technology' },
  { word: 'scanner', theme: 'device', category: 'technology' },
  { word: 'router', theme: 'device', category: 'technology' },
  { word: 'modem', theme: 'device', category: 'technology' },
  { word: 'hard drive', theme: 'device', category: 'technology' },
  { word: 'SSD', theme: 'device', category: 'technology' },
  { word: 'RAM', theme: 'component', category: 'technology' },
  { word: 'CPU', theme: 'component', category: 'technology' },
  { word: 'GPU', theme: 'component', category: 'technology' },
  { word: 'motherboard', theme: 'component', category: 'technology' },
  { word: 'power supply', theme: 'component', category: 'technology' },
  { word: 'cooling fan', theme: 'component', category: 'technology' },
  { word: 'battery', theme: 'component', category: 'technology' },
  { word: 'charger', theme: 'accessory', category: 'technology' },
  { word: 'cable', theme: 'accessory', category: 'technology' },
  { word: 'adapter', theme: 'accessory', category: 'technology' },
  { word: 'remote control', theme: 'device', category: 'technology' },
  { word: 'game controller', theme: 'device', category: 'technology' },
  { word: 'joystick', theme: 'device', category: 'technology' },
  { word: 'steering wheel', theme: 'device', category: 'technology' },
  { word: 'flight stick', theme: 'device', category: 'technology' },
  { word: 'umbrella', theme: 'item', category: 'objects' },
  { word: 'mirror', theme: 'item', category: 'objects' },
  { word: 'backpack', theme: 'item', category: 'objects' },
  { word: 'notebook', theme: 'item', category: 'objects' },
  { word: 'flashlight', theme: 'item', category: 'objects' },
  { word: 'clock', theme: 'item', category: 'objects' },
  { word: 'watch', theme: 'item', category: 'objects' },
  { word: 'bicycle', theme: 'vehicle', category: 'objects' },
  { word: 'skateboard', theme: 'vehicle', category: 'objects' },
  { word: 'scooter', theme: 'vehicle', category: 'objects' },
  { word: 'chair', theme: 'furniture', category: 'objects' },
  { word: 'table', theme: 'furniture', category: 'objects' },
  { word: 'desk', theme: 'furniture', category: 'objects' },
  { word: 'bed', theme: 'furniture', category: 'objects' },
  { word: 'couch', theme: 'furniture', category: 'objects' },
  { word: 'sofa', theme: 'furniture', category: 'objects' },
  { word: 'lamp', theme: 'furniture', category: 'objects' },
  { word: 'blanket', theme: 'item', category: 'objects' },
  { word: 'pillow', theme: 'item', category: 'objects' },
  { word: 'mattress', theme: 'item', category: 'objects' },
  { word: 'curtain', theme: 'item', category: 'objects' },
  { word: 'rug', theme: 'item', category: 'objects' },
  { word: 'carpet', theme: 'item', category: 'objects' },
  { word: 'scissors', theme: 'tool', category: 'objects' },
  { word: 'knife', theme: 'tool', category: 'objects' },
  { word: 'fork', theme: 'utensil', category: 'objects' },
  { word: 'spoon', theme: 'utensil', category: 'objects' },
  { word: 'plate', theme: 'dish', category: 'objects' },
  { word: 'bowl', theme: 'dish', category: 'objects' },
  { word: 'cup', theme: 'dish', category: 'objects' },
  { word: 'mug', theme: 'dish', category: 'objects' },
  { word: 'glass', theme: 'dish', category: 'objects' },
  { word: 'bottle', theme: 'container', category: 'objects' },
  { word: 'jar', theme: 'container', category: 'objects' },
  { word: 'can', theme: 'container', category: 'objects' },
  { word: 'box', theme: 'container', category: 'objects' },
  { word: 'bag', theme: 'container', category: 'objects' },
  { word: 'basket', theme: 'container', category: 'objects' },
  { word: 'bucket', theme: 'container', category: 'objects' },
  { word: 'trash can', theme: 'container', category: 'objects' },
  { word: 'key', theme: 'item', category: 'objects' },
  { word: 'lock', theme: 'item', category: 'objects' },
  { word: 'door', theme: 'structure', category: 'objects' },
  { word: 'window', theme: 'structure', category: 'objects' },
  { word: 'wall', theme: 'structure', category: 'objects' },
  { word: 'floor', theme: 'structure', category: 'objects' },
  { word: 'ceiling', theme: 'structure', category: 'objects' },
  { word: 'roof', theme: 'structure', category: 'objects' },
  { word: 'stairs', theme: 'structure', category: 'objects' },
  { word: 'ladder', theme: 'tool', category: 'objects' },
  { word: 'rope', theme: 'tool', category: 'objects' },
  { word: 'chain', theme: 'tool', category: 'objects' },
  { word: 'hammer', theme: 'tool', category: 'objects' },
  { word: 'screwdriver', theme: 'tool', category: 'objects' },
  { word: 'wrench', theme: 'tool', category: 'objects' },
  { word: 'drill', theme: 'tool', category: 'objects' },
  { word: 'saw', theme: 'tool', category: 'objects' },

  // --- Sports (50+ words) ---
  { word: 'soccer', theme: 'sport', category: 'sports' },
  { word: 'football', theme: 'sport', category: 'sports' },
  { word: 'basketball', theme: 'sport', category: 'sports' },
  { word: 'baseball', theme: 'sport', category: 'sports' },
  { word: 'tennis', theme: 'sport', category: 'sports' },
  { word: 'volleyball', theme: 'sport', category: 'sports' },
  { word: 'golf', theme: 'sport', category: 'sports' },
  { word: 'hockey', theme: 'sport', category: 'sports' },
  { word: 'cricket', theme: 'sport', category: 'sports' },
  { word: 'rugby', theme: 'sport', category: 'sports' },
  { word: 'bowling', theme: 'sport', category: 'sports' },
  { word: 'boxing', theme: 'sport', category: 'sports' },
  { word: 'wrestling', theme: 'sport', category: 'sports' },
  { word: 'MMA', theme: 'sport', category: 'sports' },
  { word: 'karate', theme: 'sport', category: 'sports' },
  { word: 'judo', theme: 'sport', category: 'sports' },
  { word: 'taekwondo', theme: 'sport', category: 'sports' },
  { word: 'fencing', theme: 'sport', category: 'sports' },
  { word: 'archery', theme: 'sport', category: 'sports' },
  { word: 'swimming', theme: 'sport', category: 'sports' },
  { word: 'diving', theme: 'sport', category: 'sports' },
  { word: 'surfing', theme: 'sport', category: 'sports' },
  { word: 'skiing', theme: 'sport', category: 'sports' },
  { word: 'snowboarding', theme: 'sport', category: 'sports' },
  { word: 'ice skating', theme: 'sport', category: 'sports' },
  { word: 'figure skating', theme: 'sport', category: 'sports' },
  { word: 'speed skating', theme: 'sport', category: 'sports' },
  { word: 'curling', theme: 'sport', category: 'sports' },
  { word: 'bobsled', theme: 'sport', category: 'sports' },
  { word: 'skeleton', theme: 'sport', category: 'sports' },
  { word: 'biathlon', theme: 'sport', category: 'sports' },
  { word: 'triathlon', theme: 'sport', category: 'sports' },
  { word: 'marathon', theme: 'sport', category: 'sports' },
  { word: 'sprinting', theme: 'sport', category: 'sports' },
  { word: 'hurdles', theme: 'sport', category: 'sports' },
  { word: 'long jump', theme: 'sport', category: 'sports' },
  { word: 'high jump', theme: 'sport', category: 'sports' },
  { word: 'pole vault', theme: 'sport', category: 'sports' },
  { word: 'shot put', theme: 'sport', category: 'sports' },
  { word: 'discus', theme: 'sport', category: 'sports' },
  { word: 'javelin', theme: 'sport', category: 'sports' },
  { word: 'hammer throw', theme: 'sport', category: 'sports' },
  { word: 'gymnastics', theme: 'sport', category: 'sports' },
  { word: 'cheerleading', theme: 'sport', category: 'sports' },
  { word: 'dance', theme: 'sport', category: 'sports' },
  { word: 'ballet', theme: 'sport', category: 'sports' },
  { word: 'yoga', theme: 'sport', category: 'sports' },
  { word: 'pilates', theme: 'sport', category: 'sports' },
  { word: 'crossfit', theme: 'sport', category: 'sports' },
  { word: 'weightlifting', theme: 'sport', category: 'sports' },
  { word: 'powerlifting', theme: 'sport', category: 'sports' },
  { word: 'bodybuilding', theme: 'sport', category: 'sports' },
  { word: 'cycling', theme: 'sport', category: 'sports' },
  { word: 'BMX', theme: 'sport', category: 'sports' },
  { word: 'mountain biking', theme: 'sport', category: 'sports' },
  { word: 'rock climbing', theme: 'sport', category: 'sports' },
  { word: 'parkour', theme: 'sport', category: 'sports' },

  // --- Places (40+ words) ---
  { word: 'library', theme: 'building', category: 'places' },
  { word: 'theater', theme: 'building', category: 'places' },
  { word: 'museum', theme: 'building', category: 'places' },
  { word: 'stadium', theme: 'building', category: 'places' },
  { word: 'airport', theme: 'building', category: 'places' },
  { word: 'hospital', theme: 'building', category: 'places' },
  { word: 'school', theme: 'building', category: 'places' },
  { word: 'university', theme: 'building', category: 'places' },
  { word: 'college', theme: 'building', category: 'places' },
  { word: 'church', theme: 'building', category: 'places' },
  { word: 'temple', theme: 'building', category: 'places' },
  { word: 'mosque', theme: 'building', category: 'places' },
  { word: 'synagogue', theme: 'building', category: 'places' },
  { word: 'castle', theme: 'building', category: 'places' },
  { word: 'palace', theme: 'building', category: 'places' },
  { word: 'mansion', theme: 'building', category: 'places' },
  { word: 'house', theme: 'building', category: 'places' },
  { word: 'apartment', theme: 'building', category: 'places' },
  { word: 'hotel', theme: 'building', category: 'places' },
  { word: 'motel', theme: 'building', category: 'places' },
  { word: 'restaurant', theme: 'building', category: 'places' },
  { word: 'cafe', theme: 'building', category: 'places' },
  { word: 'bakery', theme: 'building', category: 'places' },
  { word: 'grocery store', theme: 'building', category: 'places' },
  { word: 'mall', theme: 'building', category: 'places' },
  { word: 'market', theme: 'location', category: 'places' },
  { word: 'park', theme: 'location', category: 'places' },
  { word: 'playground', theme: 'location', category: 'places' },
  { word: 'zoo', theme: 'location', category: 'places' },
  { word: 'aquarium', theme: 'building', category: 'places' },
  { word: 'beach', theme: 'location', category: 'places' },
  { word: 'pool', theme: 'location', category: 'places' },
  { word: 'gym', theme: 'building', category: 'places' },
  { word: 'spa', theme: 'building', category: 'places' },
  { word: 'salon', theme: 'building', category: 'places' },
  { word: 'barbershop', theme: 'building', category: 'places' },
  { word: 'bank', theme: 'building', category: 'places' },
  { word: 'post office', theme: 'building', category: 'places' },
  { word: 'police station', theme: 'building', category: 'places' },
  { word: 'fire station', theme: 'building', category: 'places' },
  { word: 'gas station', theme: 'building', category: 'places' },
  { word: 'train station', theme: 'building', category: 'places' },
  { word: 'bus stop', theme: 'location', category: 'places' },
  { word: 'subway', theme: 'location', category: 'places' },
  { word: 'parking lot', theme: 'location', category: 'places' },
  { word: 'garage', theme: 'building', category: 'places' },
  { word: 'warehouse', theme: 'building', category: 'places' },
  { word: 'factory', theme: 'building', category: 'places' },
  { word: 'office', theme: 'building', category: 'places' },
  { word: 'skyscraper', theme: 'building', category: 'places' },

  // --- Anime (100+ words) ---
  { word: 'Naruto', theme: 'believe it', category: 'anime' },
  { word: 'One Piece', theme: 'pirate king', category: 'anime' },
  { word: 'Dragon Ball', theme: 'over 9000', category: 'anime' },
  { word: 'Attack on Titan', theme: 'walls humanity', category: 'anime' },
  { word: 'My Hero Academia', theme: 'plus ultra', category: 'anime' },
  { word: 'Demon Slayer', theme: 'water breathing', category: 'anime' },
  { word: 'Death Note', theme: 'potato chip', category: 'anime' },
  { word: 'Fullmetal Alchemist', theme: 'equivalent exchange', category: 'anime' },
  { word: 'Sword Art Online', theme: 'link start', category: 'anime' },
  { word: 'Tokyo Ghoul', theme: 'kaneki mask', category: 'anime' },
  { word: 'Hunter x Hunter', theme: 'nen ability', category: 'anime' },
  { word: 'Bleach', theme: 'bankai release', category: 'anime' },
  { word: 'One Punch Man', theme: 'ok', category: 'anime' },
  { word: 'Jujutsu Kaisen', theme: 'domain expansion', category: 'anime' },
  { word: 'Chainsaw Man', theme: 'pull cord', category: 'anime' },
  { word: 'Spy x Family', theme: 'waku waku', category: 'anime' },
  { word: 'Mob Psycho 100', theme: 'percent counter', category: 'anime' },
  { word: 'Steins Gate', theme: 'el psy', category: 'anime' },
  { word: 'Code Geass', theme: 'all hail', category: 'anime' },
  { word: 'Cowboy Bebop', theme: 'see you space', category: 'anime' },
  { word: 'Neon Genesis Evangelion', theme: 'get in robot', category: 'anime' },
  { word: 'Fairy Tail', theme: 'guild mark', category: 'anime' },
  { word: 'Black Clover', theme: 'grimoire magic', category: 'anime' },
  { word: 'Fire Force', theme: 'latom prayer', category: 'anime' },
  { word: 'Dr Stone', theme: 'ten billion percent', category: 'anime' },
  { word: 'Assassination Classroom', theme: 'yellow octopus', category: 'anime' },
  { word: 'The Promised Neverland', theme: 'escape plan', category: 'anime' },
  { word: 'Haikyuu', theme: 'fly high', category: 'anime' },
  { word: 'Kuroko no Basket', theme: 'phantom sixth', category: 'anime' },
  { word: 'Blue Lock', theme: 'ego striker', category: 'anime' },
  { word: 'Slam Dunk', theme: 'series', category: 'anime' },
  { word: 'Yu Yu Hakusho', theme: 'series', category: 'anime' },
  { word: 'Inuyasha', theme: 'series', category: 'anime' },
  { word: 'Sailor Moon', theme: 'series', category: 'anime' },
  { word: 'Cardcaptor Sakura', theme: 'series', category: 'anime' },
  { word: 'Fruits Basket', theme: 'series', category: 'anime' },
  { word: 'Ouran High School Host Club', theme: 'series', category: 'anime' },
  { word: 'Toradora', theme: 'series', category: 'anime' },
  { word: 'Your Lie in April', theme: 'series', category: 'anime' },
  { word: 'Clannad', theme: 'series', category: 'anime' },
  { word: 'Angel Beats', theme: 'series', category: 'anime' },
  { word: 'Anohana', theme: 'series', category: 'anime' },
  { word: 'Your Name', theme: 'film', category: 'anime' },
  { word: 'Weathering With You', theme: 'film', category: 'anime' },
  { word: 'A Silent Voice', theme: 'film', category: 'anime' },
  { word: 'Spirited Away', theme: 'film', category: 'anime' },
  { word: 'My Neighbor Totoro', theme: 'film', category: 'anime' },
  { word: 'Howls Moving Castle', theme: 'film', category: 'anime' },
  { word: 'Princess Mononoke', theme: 'film', category: 'anime' },
  { word: 'Ponyo', theme: 'film', category: 'anime' },
  { word: 'Kiki Delivery Service', theme: 'film', category: 'anime' },
  { word: 'Castle in the Sky', theme: 'film', category: 'anime' },
  { word: 'Akira', theme: 'film', category: 'anime' },
  { word: 'Ghost in the Shell', theme: 'film', category: 'anime' },
  { word: 'Perfect Blue', theme: 'film', category: 'anime' },
  { word: 'Paprika', theme: 'film', category: 'anime' },
  { word: 'Tokyo Godfathers', theme: 'film', category: 'anime' },
  { word: 'Violet Evergarden', theme: 'series', category: 'anime' },
  { word: 'Re:Zero', theme: 'series', category: 'anime' },
  { word: 'Konosuba', theme: 'series', category: 'anime' },
  { word: 'Overlord', theme: 'series', category: 'anime' },
  { word: 'That Time I Got Reincarnated as a Slime', theme: 'series', category: 'anime' },
  { word: 'No Game No Life', theme: 'series', category: 'anime' },
  { word: 'The Rising of the Shield Hero', theme: 'series', category: 'anime' },
  { word: 'Goblin Slayer', theme: 'series', category: 'anime' },
  { word: 'Made in Abyss', theme: 'series', category: 'anime' },
  { word: 'Vinland Saga', theme: 'series', category: 'anime' },
  { word: 'Berserk', theme: 'series', category: 'anime' },
  { word: 'Vagabond', theme: 'series', category: 'anime' },
  { word: 'Monster', theme: 'series', category: 'anime' },
  { word: 'Parasyte', theme: 'series', category: 'anime' },
  { word: 'Elfen Lied', theme: 'series', category: 'anime' },
  { word: 'Mirai Nikki', theme: 'series', category: 'anime' },
  { word: 'Another', theme: 'series', category: 'anime' },
  { word: 'Higurashi', theme: 'series', category: 'anime' },
  { word: 'Hellsing', theme: 'series', category: 'anime' },
  { word: 'Black Lagoon', theme: 'series', category: 'anime' },
  { word: 'Trigun', theme: 'series', category: 'anime' },
  { word: 'Samurai Champloo', theme: 'series', category: 'anime' },
  { word: 'Space Dandy', theme: 'series', category: 'anime' },
  { word: 'Gurren Lagann', theme: 'series', category: 'anime' },
  { word: 'Kill la Kill', theme: 'series', category: 'anime' },
  { word: 'Darling in the Franxx', theme: 'series', category: 'anime' },
  { word: 'Sword of the Stranger', theme: 'film', category: 'anime' },
  { word: 'Redline', theme: 'film', category: 'anime' },
  { word: 'Summer Wars', theme: 'film', category: 'anime' },
  { word: 'The Girl Who Leapt Through Time', theme: 'film', category: 'anime' },
  { word: 'Wolf Children', theme: 'film', category: 'anime' },
  { word: 'Goku', theme: 'character', category: 'anime' },
  { word: 'Vegeta', theme: 'character', category: 'anime' },
  { word: 'Luffy', theme: 'character', category: 'anime' },
  { word: 'Zoro', theme: 'character', category: 'anime' },
  { word: 'Sanji', theme: 'character', category: 'anime' },
  { word: 'Nami', theme: 'character', category: 'anime' },
  { word: 'Naruto Uzumaki', theme: 'character', category: 'anime' },
  { word: 'Sasuke', theme: 'character', category: 'anime' },
  { word: 'Sakura', theme: 'character', category: 'anime' },
  { word: 'Kakashi', theme: 'character', category: 'anime' },
  { word: 'Itachi', theme: 'character', category: 'anime' },
  { word: 'Madara', theme: 'character', category: 'anime' },
  { word: 'Eren Yeager', theme: 'character', category: 'anime' },
  { word: 'Mikasa', theme: 'character', category: 'anime' },
  { word: 'Levi', theme: 'character', category: 'anime' },
  { word: 'Armin', theme: 'character', category: 'anime' },
  { word: 'Light Yagami', theme: 'character', category: 'anime' },
  { word: 'L', theme: 'character', category: 'anime' },
  { word: 'Ryuk', theme: 'character', category: 'anime' },
  { word: 'Edward Elric', theme: 'character', category: 'anime' },
  { word: 'Alphonse Elric', theme: 'character', category: 'anime' },
  { word: 'Roy Mustang', theme: 'character', category: 'anime' },
  { word: 'Saitama', theme: 'character', category: 'anime' },
  { word: 'Genos', theme: 'character', category: 'anime' },
  { word: 'Tanjiro', theme: 'character', category: 'anime' },
  { word: 'Nezuko', theme: 'character', category: 'anime' },
  { word: 'Zenitsu', theme: 'character', category: 'anime' },
  { word: 'Inosuke', theme: 'character', category: 'anime' },
  { word: 'Deku', theme: 'character', category: 'anime' },
  { word: 'All Might', theme: 'character', category: 'anime' },
  { word: 'Bakugo', theme: 'character', category: 'anime' },
  { word: 'Todoroki', theme: 'character', category: 'anime' },
  { word: 'Kirito', theme: 'character', category: 'anime' },
  { word: 'Asuna', theme: 'character', category: 'anime' },
  { word: 'Gon', theme: 'character', category: 'anime' },
  { word: 'Killua', theme: 'character', category: 'anime' },
  { word: 'Ichigo', theme: 'character', category: 'anime' },
  { word: 'Rukia', theme: 'character', category: 'anime' },
  { word: 'Aizen', theme: 'character', category: 'anime' },
  { word: 'Spike Spiegel', theme: 'character', category: 'anime' },
  { word: 'Faye Valentine', theme: 'character', category: 'anime' },
  { word: 'Lelouch', theme: 'character', category: 'anime' },
  { word: 'C.C.', theme: 'character', category: 'anime' },
  { word: 'Shinji Ikari', theme: 'character', category: 'anime' },
  { word: 'Rei Ayanami', theme: 'character', category: 'anime' },
  { word: 'Asuka', theme: 'character', category: 'anime' },

  // --- Abstract Concepts (30+ words) ---
  { word: 'freedom', theme: 'concept', category: 'abstract' },
  { word: 'love', theme: 'emotion', category: 'abstract' },
  { word: 'hate', theme: 'emotion', category: 'abstract' },
  { word: 'happiness', theme: 'emotion', category: 'abstract' },
  { word: 'sadness', theme: 'emotion', category: 'abstract' },
  { word: 'anger', theme: 'emotion', category: 'abstract' },
  { word: 'fear', theme: 'emotion', category: 'abstract' },
  { word: 'joy', theme: 'emotion', category: 'abstract' },
  { word: 'peace', theme: 'concept', category: 'abstract' },
  { word: 'war', theme: 'concept', category: 'abstract' },
  { word: 'justice', theme: 'concept', category: 'abstract' },
  { word: 'truth', theme: 'concept', category: 'abstract' },
  { word: 'lie', theme: 'concept', category: 'abstract' },
  { word: 'trust', theme: 'concept', category: 'abstract' },
  { word: 'betrayal', theme: 'concept', category: 'abstract' },
  { word: 'hope', theme: 'emotion', category: 'abstract' },
  { word: 'despair', theme: 'emotion', category: 'abstract' },
  { word: 'courage', theme: 'concept', category: 'abstract' },
  { word: 'cowardice', theme: 'concept', category: 'abstract' },
  { word: 'wisdom', theme: 'concept', category: 'abstract' },
  { word: 'knowledge', theme: 'concept', category: 'abstract' },
  { word: 'ignorance', theme: 'concept', category: 'abstract' },
  { word: 'power', theme: 'concept', category: 'abstract' },
  { word: 'weakness', theme: 'concept', category: 'abstract' },
  { word: 'strength', theme: 'concept', category: 'abstract' },
  { word: 'beauty', theme: 'concept', category: 'abstract' },
  { word: 'ugliness', theme: 'concept', category: 'abstract' },
  { word: 'time', theme: 'concept', category: 'abstract' },
  { word: 'space', theme: 'concept', category: 'abstract' },
  { word: 'infinity', theme: 'concept', category: 'abstract' },
  { word: 'eternity', theme: 'concept', category: 'abstract' },
  { word: 'life', theme: 'concept', category: 'abstract' },
  { word: 'death', theme: 'concept', category: 'abstract' },
  { word: 'birth', theme: 'concept', category: 'abstract' },
  { word: 'destiny', theme: 'concept', category: 'abstract' },
  { word: 'fate', theme: 'concept', category: 'abstract' },
  { word: 'luck', theme: 'concept', category: 'abstract' },
  { word: 'chance', theme: 'concept', category: 'abstract' },
  { word: 'chaos', theme: 'concept', category: 'abstract' },
  { word: 'order', theme: 'concept', category: 'abstract' },
  { word: 'balance', theme: 'concept', category: 'abstract' },
  { word: 'harmony', theme: 'concept', category: 'abstract' },
  { word: 'discord', theme: 'concept', category: 'abstract' },
  { word: 'silence', theme: 'concept', category: 'abstract' },
  { word: 'noise', theme: 'concept', category: 'abstract' },
  { word: 'light', theme: 'concept', category: 'abstract' },
  { word: 'darkness', theme: 'concept', category: 'abstract' },
  { word: 'shadow', theme: 'concept', category: 'abstract' },
  { word: 'dream', theme: 'concept', category: 'abstract' },
  { word: 'nightmare', theme: 'concept', category: 'abstract' },
  { word: 'reality', theme: 'concept', category: 'abstract' },
  { word: 'illusion', theme: 'concept', category: 'abstract' },
  { word: 'memory', theme: 'concept', category: 'abstract' },
  { word: 'imagination', theme: 'concept', category: 'abstract' },
];

// Category definitions for the dropdown
const CATEGORIES = {
  all: { name: 'All Categories', filter: null },
  food: { name: 'Food & Drinks', filter: 'food' },
  animals: { name: 'Animals', filter: 'animals' },
  nature: { name: 'Nature & Weather', filter: 'nature' },
  videogames: { name: 'Video Games', filter: 'videogames' },
  music: { name: 'Music Artists', filter: 'music' },
  memes: { name: 'Memes & Internet', filter: 'memes' },
  movies: { name: 'Movies & TV', filter: 'movies' },
  anime: { name: 'Anime', filter: 'anime' },
  technology: { name: 'Technology', filter: 'technology' },
  sports: { name: 'Sports', filter: 'sports' },
  objects: { name: 'Everyday Objects', filter: 'objects' },
  places: { name: 'Places', filter: 'places' },
  abstract: { name: 'Abstract Concepts', filter: 'abstract' },
};

function getRandomWord(categoryFilter = null) {
  let filteredWords = WORDS;
  
  if (categoryFilter && categoryFilter !== 'all') {
    filteredWords = WORDS.filter(w => w.category === categoryFilter);
  }
  
  if (filteredWords.length === 0) {
    filteredWords = WORDS; // Fallback to all words
  }
  
  return filteredWords[Math.floor(Math.random() * filteredWords.length)];
}

function getRandomWordFromList(wordStrings) {
  if (!wordStrings || wordStrings.length === 0) return null;
  const word = wordStrings[Math.floor(Math.random() * wordStrings.length)].trim();
  if (!word) return getRandomWordFromList(wordStrings.filter(Boolean));
  return { word, theme: 'Custom', category: null };
}

// Basic impostor clue generator.
// It returns a clue that is related but not identical.
function generateImpostorClue(entry) {
  if (!entry) return 'Something related to a secret word.';

  // Prefer a high-level category clue if available.
  if (entry.category) {
    return `Something related to ${entry.category}.`;
  }

  // Fall back to the theme text but soften it slightly.
  if (entry.theme) {
    return `Think about ${entry.theme}, but not too specific.`;
  }

  // Very generic backup.
  return 'Closely related to the secret word, but different.';
}

module.exports = {
  WORDS,
  CATEGORIES,
  getRandomWord,
  getRandomWordFromList,
  generateImpostorClue,
};
