// Anime words

module.exports = [
  { word: 'Naruto', theme: 'show', category: 'anime' },
  { word: 'One Piece', theme: 'show', category: 'anime' },
  { word: 'Dragon Ball', theme: 'show', category: 'anime' },
  { word: 'Attack on Titan', theme: 'show', category: 'anime' },
  { word: 'My Hero Academia', theme: 'show', category: 'anime' },
  { word: 'Demon Slayer', theme: 'show', category: 'anime' },
  { word: 'Death Note', theme: 'show', category: 'anime' },
  { word: 'Fullmetal Alchemist', theme: 'show', category: 'anime' },
  { word: 'Sword Art Online', theme: 'show', category: 'anime' },
  { word: 'Tokyo Ghoul', theme: 'show', category: 'anime' },
  { word: 'Hunter x Hunter', theme: 'show', category: 'anime' },
  { word: 'Bleach', theme: 'show', category: 'anime' },
  { word: 'One Punch Man', theme: 'show', category: 'anime' },
  { word: 'Jujutsu Kaisen', theme: 'show', category: 'anime' },
  { word: 'Chainsaw Man', theme: 'show', category: 'anime' },
  { word: 'Spy x Family', theme: 'show', category: 'anime' },
  { word: 'Mob Psycho 100', theme: 'show', category: 'anime' },
  { word: 'Steins Gate', theme: 'show', category: 'anime' },
  { word: 'Code Geass', theme: 'show', category: 'anime' },
  { word: 'Cowboy Bebop', theme: 'show', category: 'anime' },
  { word: 'Neon Genesis Evangelion', theme: 'show', category: 'anime' },
  { word: 'Fairy Tail', theme: 'show', category: 'anime' },
  { word: 'Black Clover', theme: 'show', category: 'anime' },
  { word: 'Fire Force', theme: 'show', category: 'anime' },
  { word: 'Dr Stone', theme: 'show', category: 'anime' },
  { word: 'Assassination Classroom', theme: 'show', category: 'anime' },
  { word: 'The Promised Neverland', theme: 'show', category: 'anime' },
  { word: 'Haikyuu', theme: 'show', category: 'anime' },
  { word: 'Kuroko no Basket', theme: 'show', category: 'anime' },
  { word: 'Blue Lock', theme: 'show', category: 'anime' },
  { word: 'Slam Dunk', theme: 'show', category: 'anime' },
  { word: 'Yu Yu Hakusho', theme: 'show', category: 'anime' },
  { word: 'Inuyasha', theme: 'show', category: 'anime' },
  { word: 'Sailor Moon', theme: 'show', category: 'anime' },
  { word: 'Cardcaptor Sakura', theme: 'show', category: 'anime' },
  { word: 'Fruits Basket', theme: 'show', category: 'anime' },
  { word: 'Ouran High School Host Club', theme: 'show', category: 'anime' },
  { word: 'Toradora', theme: 'show', category: 'anime' },
  { word: 'Your Lie in April', theme: 'show', category: 'anime' },
  { word: 'Clannad', theme: 'show', category: 'anime' },
  { word: 'Angel Beats', theme: 'show', category: 'anime' },
  { word: 'Anohana', theme: 'show', category: 'anime' },
  { word: 'Your Name', theme: 'show', category: 'anime' },
  { word: 'Weathering With You', theme: 'show', category: 'anime' },
  { word: 'A Silent Voice', theme: 'show', category: 'anime' },
  { word: 'Spirited Away', theme: 'show', category: 'anime' },
  { word: 'My Neighbor Totoro', theme: 'show', category: 'anime' },
  { word: 'Howls Moving Castle', theme: 'show', category: 'anime' },
  { word: 'Princess Mononoke', theme: 'show', category: 'anime' },
  { word: 'Ponyo', theme: 'show', category: 'anime' },
  { word: 'Kiki Delivery Service', theme: 'show', category: 'anime' },
  { word: 'Castle in the Sky', theme: 'show', category: 'anime' },
  { word: 'Akira', theme: 'show', category: 'anime' },
  { word: 'Ghost in the Shell', theme: 'show', category: 'anime' },
  { word: 'Perfect Blue', theme: 'show', category: 'anime' },
  { word: 'Paprika', theme: 'show', category: 'anime' },
  { word: 'Tokyo Godfathers', theme: 'show', category: 'anime' },
  { word: 'Violet Evergarden', theme: 'show', category: 'anime' },
  { word: 'Re:Zero', theme: 'show', category: 'anime' },
  { word: 'Konosuba', theme: 'show', category: 'anime' },
  { word: 'Overlord', theme: 'show', category: 'anime' },
  { word: 'That Time I Got Reincarnated as a Slime', theme: 'show', category: 'anime' },
  { word: 'No Game No Life', theme: 'show', category: 'anime' },
  { word: 'The Rising of the Shield Hero', theme: 'show', category: 'anime' },
  { word: 'Goblin Slayer', theme: 'show', category: 'anime' },
  { word: 'Made in Abyss', theme: 'show', category: 'anime' },
  { word: 'Vinland Saga', theme: 'show', category: 'anime' },
  { word: 'Berserk', theme: 'show', category: 'anime' },
  { word: 'Vagabond', theme: 'show', category: 'anime' },
  { word: 'Monster', theme: 'show', category: 'anime' },
  { word: 'Parasyte', theme: 'show', category: 'anime' },
  { word: 'Elfen Lied', theme: 'show', category: 'anime' },
  { word: 'Mirai Nikki', theme: 'show', category: 'anime' },
  { word: 'Another', theme: 'show', category: 'anime' },
  { word: 'Higurashi', theme: 'show', category: 'anime' },
  { word: 'Hellsing', theme: 'show', category: 'anime' },
  { word: 'Black Lagoon', theme: 'show', category: 'anime' },
  { word: 'Trigun', theme: 'show', category: 'anime' },
  { word: 'Samurai Champloo', theme: 'show', category: 'anime' },
  { word: 'Space Dandy', theme: 'show', category: 'anime' },
  { word: 'Gurren Lagann', theme: 'show', category: 'anime' },
  { word: 'Kill la Kill', theme: 'show', category: 'anime' },
  { word: 'Darling in the Franxx', theme: 'show', category: 'anime' },
  { word: 'Sword of the Stranger', theme: 'show', category: 'anime' },
  { word: 'Redline', theme: 'show', category: 'anime' },
  { word: 'Summer Wars', theme: 'show', category: 'anime' },
  { word: 'The Girl Who Leapt Through Time', theme: 'show', category: 'anime' },
  { word: 'Wolf Children', theme: 'show', category: 'anime' },
  { word: 'Goku', theme: 'show', category: 'anime' },
  { word: 'Vegeta', theme: 'show', category: 'anime' },
  { word: 'Luffy', theme: 'show', category: 'anime' },
  { word: 'Zoro', theme: 'show', category: 'anime' },
  { word: 'Sanji', theme: 'show', category: 'anime' },
  { word: 'Nami', theme: 'show', category: 'anime' },
  { word: 'Naruto Uzumaki', theme: 'show', category: 'anime' },
  { word: 'Sasuke', theme: 'show', category: 'anime' },
  { word: 'Sakura', theme: 'show', category: 'anime' },
  { word: 'Kakashi', theme: 'show', category: 'anime' },
  { word: 'Itachi', theme: 'show', category: 'anime' },
  { word: 'Madara', theme: 'show', category: 'anime' },
  { word: 'Eren Yeager', theme: 'show', category: 'anime' },
  { word: 'Mikasa', theme: 'show', category: 'anime' },
  { word: 'Levi', theme: 'show', category: 'anime' },
  { word: 'Armin', theme: 'show', category: 'anime' },
  { word: 'Light Yagami', theme: 'show', category: 'anime' },
  { word: 'L', theme: 'show', category: 'anime' },
  { word: 'Ryuk', theme: 'show', category: 'anime' },
  { word: 'Edward Elric', theme: 'show', category: 'anime' },
  { word: 'Alphonse Elric', theme: 'show', category: 'anime' },
  { word: 'Roy Mustang', theme: 'show', category: 'anime' },
  { word: 'Saitama', theme: 'show', category: 'anime' },
  { word: 'Genos', theme: 'show', category: 'anime' },
  { word: 'Tanjiro', theme: 'show', category: 'anime' },
  { word: 'Nezuko', theme: 'show', category: 'anime' },
  { word: 'Zenitsu', theme: 'show', category: 'anime' },
  { word: 'Inosuke', theme: 'show', category: 'anime' },
  { word: 'Deku', theme: 'show', category: 'anime' },
  { word: 'All Might', theme: 'show', category: 'anime' },
  { word: 'Bakugo', theme: 'show', category: 'anime' },
  { word: 'Todoroki', theme: 'show', category: 'anime' },
  { word: 'Kirito', theme: 'show', category: 'anime' },
  { word: 'Asuna', theme: 'show', category: 'anime' },
  { word: 'Gon', theme: 'show', category: 'anime' },
  { word: 'Killua', theme: 'show', category: 'anime' },
  { word: 'Ichigo', theme: 'show', category: 'anime' },
  { word: 'Rukia', theme: 'show', category: 'anime' },
  { word: 'Aizen', theme: 'show', category: 'anime' },
  { word: 'Spike Spiegel', theme: 'show', category: 'anime' },
  { word: 'Faye Valentine', theme: 'show', category: 'anime' },
  { word: 'Lelouch', theme: 'show', category: 'anime' },
  { word: 'C.C.', theme: 'show', category: 'anime' },
  { word: 'Shinji Ikari', theme: 'show', category: 'anime' },
  { word: 'Rei Ayanami', theme: 'show', category: 'anime' },
  { word: 'Asuka', theme: 'show', category: 'anime' },
];
