// Food words

module.exports = [
  { word: 'chocolate', theme: 'edible', category: 'food' },
  { word: 'sushi', theme: 'edible', category: 'food' },
  { word: 'pizza', theme: 'edible', category: 'food' },
  { word: 'hamburger', theme: 'edible', category: 'food' },
  { word: 'pancake', theme: 'edible', category: 'food' },
  { word: 'spaghetti', theme: 'edible', category: 'food' },
  { word: 'taco', theme: 'edible', category: 'food' },
  { word: 'ice cream', theme: 'edible', category: 'food' },
  { word: 'salad', theme: 'edible', category: 'food' },
  { word: 'croissant', theme: 'edible', category: 'food' },
  { word: 'ramen', theme: 'edible', category: 'food' },
  { word: 'soup', theme: 'edible', category: 'food' },
  { word: 'burrito', theme: 'edible', category: 'food' },
  { word: 'donut', theme: 'edible', category: 'food' },
  { word: 'waffle', theme: 'edible', category: 'food' },
  { word: 'curry', theme: 'edible', category: 'food' },
  { word: 'sandwich', theme: 'edible', category: 'food' },
  { word: 'steak', theme: 'edible', category: 'food' },
  { word: 'bacon', theme: 'edible', category: 'food' },
  { word: 'chicken', theme: 'edible', category: 'food' },
  { word: 'salmon', theme: 'edible', category: 'food' },
  { word: 'shrimp', theme: 'edible', category: 'food' },
  { word: 'lobster', theme: 'edible', category: 'food' },
  { word: 'crab', theme: 'edible', category: 'food' },
  { word: 'oyster', theme: 'edible', category: 'food' },
  { word: 'cheese', theme: 'edible', category: 'food' },
  { word: 'yogurt', theme: 'edible', category: 'food' },
  { word: 'milk', theme: 'edible', category: 'food' },
  { word: 'coffee', theme: 'edible', category: 'food' },
  { word: 'tea', theme: 'edible', category: 'food' },
  { word: 'juice', theme: 'edible', category: 'food' },
  { word: 'soda', theme: 'edible', category: 'food' },
  { word: 'smoothie', theme: 'edible', category: 'food' },
  { word: 'milkshake', theme: 'edible', category: 'food' },
  { word: 'lemonade', theme: 'edible', category: 'food' },
  { word: 'apple', theme: 'edible', category: 'food' },
  { word: 'banana', theme: 'edible', category: 'food' },
  { word: 'orange', theme: 'edible', category: 'food' },
  { word: 'strawberry', theme: 'edible', category: 'food' },
  { word: 'blueberry', theme: 'edible', category: 'food' },
  { word: 'grape', theme: 'edible', category: 'food' },
  { word: 'watermelon', theme: 'edible', category: 'food' },
  { word: 'pineapple', theme: 'edible', category: 'food' },
  { word: 'mango', theme: 'edible', category: 'food' },
  { word: 'avocado', theme: 'edible', category: 'food' },
  { word: 'tomato', theme: 'edible', category: 'food' },
  { word: 'potato', theme: 'edible', category: 'food' },
  { word: 'carrot', theme: 'edible', category: 'food' },
  { word: 'broccoli', theme: 'edible', category: 'food' },
  { word: 'cucumber', theme: 'edible', category: 'food' },
  { word: 'onion', theme: 'edible', category: 'food' },
  { word: 'garlic', theme: 'edible', category: 'food' },
  { word: 'pepper', theme: 'edible', category: 'food' },
  { word: 'corn', theme: 'edible', category: 'food' },
  { word: 'rice', theme: 'edible', category: 'food' },
  { word: 'bread', theme: 'edible', category: 'food' },
  { word: 'bagel', theme: 'edible', category: 'food' },
  { word: 'muffin', theme: 'edible', category: 'food' },
  { word: 'cookie', theme: 'edible', category: 'food' },
  { word: 'cake', theme: 'edible', category: 'food' },
  { word: 'pie', theme: 'edible', category: 'food' },
  { word: 'brownie', theme: 'edible', category: 'food' },
  { word: 'candy', theme: 'edible', category: 'food' },
  { word: 'gum', theme: 'edible', category: 'food' },
  { word: 'popcorn', theme: 'edible', category: 'food' },
  { word: 'chips', theme: 'edible', category: 'food' },
  { word: 'pretzel', theme: 'edible', category: 'food' },
  { word: 'nachos', theme: 'edible', category: 'food' },
  { word: 'peanut butter', theme: 'edible', category: 'food' },
  { word: 'jelly', theme: 'edible', category: 'food' },
  { word: 'honey', theme: 'edible', category: 'food' },
  { word: 'syrup', theme: 'edible', category: 'food' },
  { word: 'ketchup', theme: 'edible', category: 'food' },
  { word: 'mustard', theme: 'edible', category: 'food' },
  { word: 'mayonnaise', theme: 'edible', category: 'food' },
  { word: 'hot dog', theme: 'edible', category: 'food' },
  { word: 'french fries', theme: 'edible', category: 'food' },
  { word: 'onion rings', theme: 'edible', category: 'food' },
  { word: 'coleslaw', theme: 'edible', category: 'food' },
  { word: 'mashed potatoes', theme: 'edible', category: 'food' },
  { word: 'mac and cheese', theme: 'edible', category: 'food' },
  { word: 'lasagna', theme: 'edible', category: 'food' },
  { word: 'ravioli', theme: 'edible', category: 'food' },
  { word: 'fettuccine', theme: 'edible', category: 'food' },
  { word: 'pho', theme: 'edible', category: 'food' },
  { word: 'dumpling', theme: 'edible', category: 'food' },
  { word: 'spring roll', theme: 'edible', category: 'food' },
  { word: 'tempura', theme: 'edible', category: 'food' },
  { word: 'kebab', theme: 'edible', category: 'food' },
  { word: 'falafel', theme: 'edible', category: 'food' },
  { word: 'hummus', theme: 'edible', category: 'food' },
  { word: 'guacamole', theme: 'edible', category: 'food' },
  { word: 'salsa', theme: 'edible', category: 'food' },
  { word: 'queso', theme: 'edible', category: 'food' },
  { word: 'enchilada', theme: 'edible', category: 'food' },
  { word: 'quesadilla', theme: 'edible', category: 'food' },
  { word: 'chimichanga', theme: 'edible', category: 'food' },
  { word: 'paella', theme: 'edible', category: 'food' },
  { word: 'risotto', theme: 'edible', category: 'food' },
  { word: 'gnocchi', theme: 'edible', category: 'food' },
  { word: 'tiramisu', theme: 'edible', category: 'food' },
  { word: 'gelato', theme: 'edible', category: 'food' },
  { word: 'sorbet', theme: 'edible', category: 'food' },
  { word: 'pudding', theme: 'edible', category: 'food' },
  { word: 'cheesecake', theme: 'edible', category: 'food' },
  { word: 'cupcake', theme: 'edible', category: 'food' },
  { word: 'macaron', theme: 'edible', category: 'food' },
  { word: 'eclair', theme: 'edible', category: 'food' },
  { word: 'crepe', theme: 'edible', category: 'food' },
  { word: 'baguette', theme: 'edible', category: 'food' },
  { word: 'pretzel', theme: 'edible', category: 'food' },
  { word: 'tortilla', theme: 'edible', category: 'food' },
  { word: 'naan', theme: 'edible', category: 'food' },
  { word: 'pita', theme: 'edible', category: 'food' },
];
