// Memes words

module.exports = [
  { word: 'Skibidi Toilet', theme: 'internet', category: 'memes' },
  { word: 'Rizz', theme: 'internet', category: 'memes' },
  { word: 'Sigma Male', theme: 'internet', category: 'memes' },
  { word: 'Gyat', theme: 'internet', category: 'memes' },
  { word: 'Ohio', theme: 'internet', category: 'memes' },
  { word: 'Fanum Tax', theme: 'internet', category: 'memes' },
  { word: 'Grimace Shake', theme: 'internet', category: 'memes' },
  { word: 'Giga Chad', theme: 'internet', category: 'memes' },
  { word: 'Sigma Face', theme: 'internet', category: 'memes' },
  { word: 'Mewing', theme: 'internet', category: 'memes' },
  { word: 'Looksmaxxing', theme: 'internet', category: 'memes' },
  { word: 'Mogging', theme: 'internet', category: 'memes' },
  { word: 'Aura Points', theme: 'internet', category: 'memes' },
  { word: 'NPC', theme: 'internet', category: 'memes' },
  { word: 'Main Character', theme: 'internet', category: 'memes' },
  { word: 'Its Giving', theme: 'internet', category: 'memes' },
  { word: 'Slay', theme: 'internet', category: 'memes' },
  { word: 'No Cap', theme: 'internet', category: 'memes' },
  { word: 'Bussin', theme: 'internet', category: 'memes' },
  { word: 'Sheesh', theme: 'internet', category: 'memes' },
  { word: 'Caught in 4K', theme: 'internet', category: 'memes' },
  { word: 'Ratio', theme: 'internet', category: 'memes' },
  { word: 'Touch Grass', theme: 'internet', category: 'memes' },
  { word: 'Chronically Online', theme: 'internet', category: 'memes' },
  { word: 'Unhinged', theme: 'internet', category: 'memes' },
  { word: 'Delulu', theme: 'internet', category: 'memes' },
  { word: 'Snatched', theme: 'internet', category: 'memes' },
  { word: 'Periodt', theme: 'internet', category: 'memes' },
  { word: 'Ick', theme: 'internet', category: 'memes' },
  { word: 'Red Flag', theme: 'internet', category: 'memes' },
  { word: 'Green Flag', theme: 'internet', category: 'memes' },
  { word: 'Beige Flag', theme: 'internet', category: 'memes' },
  { word: 'Vibe Check', theme: 'internet', category: 'memes' },
  { word: 'POV', theme: 'internet', category: 'memes' },
  { word: 'This You', theme: 'internet', category: 'memes' },
  { word: 'Main Character Syndrome', theme: 'internet', category: 'memes' },
  { word: 'Rent Free', theme: 'internet', category: 'memes' },
  { word: 'Its the For Me', theme: 'internet', category: 'memes' },
  { word: 'Not the', theme: 'internet', category: 'memes' },
  { word: 'Chefs Kiss', theme: 'internet', category: 'memes' },
  { word: 'Hits Different', theme: 'internet', category: 'memes' },
  { word: 'Down Bad', theme: 'internet', category: 'memes' },
  { word: 'Simp', theme: 'internet', category: 'memes' },
  { word: 'Stan', theme: 'internet', category: 'memes' },
  { word: 'Oomf', theme: 'internet', category: 'memes' },
  { word: 'Moots', theme: 'internet', category: 'memes' },
  { word: 'Bestie', theme: 'internet', category: 'memes' },
  { word: 'Bffr', theme: 'internet', category: 'memes' },
  { word: 'Iykyk', theme: 'internet', category: 'memes' },
  { word: 'Hear Me Out', theme: 'internet', category: 'memes' },
  { word: 'Roman Empire', theme: 'internet', category: 'memes' },
  { word: 'Girl Math', theme: 'internet', category: 'memes' },
  { word: 'Girl Dinner', theme: 'internet', category: 'memes' },
  { word: 'Bed Rotting', theme: 'internet', category: 'memes' },
  { word: 'Doom Scrolling', theme: 'internet', category: 'memes' },
  { word: 'Brain Rot', theme: 'internet', category: 'memes' },
  { word: 'Core Memory', theme: 'internet', category: 'memes' },
  { word: 'Intrusive Thoughts', theme: 'internet', category: 'memes' },
  { word: 'Let Him Cook', theme: 'internet', category: 'memes' },
  { word: 'We Are So Back', theme: 'internet', category: 'memes' },
  { word: 'Its Over', theme: 'internet', category: 'memes' },
  { word: 'Cooked', theme: 'internet', category: 'memes' },
  { word: 'Locked In', theme: 'internet', category: 'memes' },
  { word: 'Goofy Ahh', theme: 'internet', category: 'memes' },
  { word: 'Nah Id Win', theme: 'internet', category: 'memes' },
  { word: 'Lobotomy Kaisen', theme: 'internet', category: 'memes' },
  { word: 'Gooning', theme: 'internet', category: 'memes' },
  { word: 'Edging', theme: 'internet', category: 'memes' },
  { word: 'Goated', theme: 'internet', category: 'memes' },
  { word: 'Mid', theme: 'internet', category: 'memes' },
  { word: 'Peak Fiction', theme: 'internet', category: 'memes' },
  { word: 'Kino', theme: 'internet', category: 'memes' },
  { word: 'Rage Comic', theme: 'internet', category: 'memes' },
  { word: 'Forever Alone', theme: 'internet', category: 'memes' },
  { word: 'Yao Ming', theme: 'internet', category: 'memes' },
  { word: 'Kobe Bryant', theme: 'internet', category: 'memes' },
  { word: 'Buzz Lightyear', theme: 'internet', category: 'memes' },
  { word: 'Mr Incredible', theme: 'internet', category: 'memes' },
  { word: 'Megamind', theme: 'internet', category: 'memes' },
  { word: 'Gru', theme: 'internet', category: 'memes' },
  { word: 'Minions', theme: 'internet', category: 'memes' },
  { word: 'Thanos', theme: 'internet', category: 'memes' },
  { word: 'Smurf Cat', theme: 'internet', category: 'memes' },
  { word: 'Quandale Dingle', theme: 'internet', category: 'memes' },
  { word: 'Goofy Ahh Uncle', theme: 'internet', category: 'memes' },
  { word: 'Huggy Wuggy', theme: 'internet', category: 'memes' },
  { word: 'Poppy Playtime', theme: 'internet', category: 'memes' },
  { word: 'Backrooms', theme: 'internet', category: 'memes' },
  { word: 'Liminal Space', theme: 'internet', category: 'memes' },
  { word: 'Uncanny Valley', theme: 'internet', category: 'memes' },
  { word: 'Mandela Catalogue', theme: 'internet', category: 'memes' },
  { word: 'Analog Horror', theme: 'internet', category: 'memes' },
  { word: 'Siren Head', theme: 'internet', category: 'memes' },
  { word: 'SCP Foundation', theme: 'internet', category: 'memes' },
  { word: 'Creepypasta', theme: 'internet', category: 'memes' },
  { word: 'Slenderman', theme: 'internet', category: 'memes' },
  { word: 'Jeff The Killer', theme: 'internet', category: 'memes' },
  { word: 'Sonic EXE', theme: 'internet', category: 'memes' },
  { word: 'Freddy Fazbear', theme: 'internet', category: 'memes' },
  { word: 'Among Us Drip', theme: 'internet', category: 'memes' },
  { word: 'Big Floppa', theme: 'internet', category: 'memes' },
  { word: 'Bingus', theme: 'internet', category: 'memes' },
  { word: 'Walter Dog', theme: 'internet', category: 'memes' },
  { word: 'Cheems', theme: 'internet', category: 'memes' },
  { word: 'Doge', theme: 'internet', category: 'memes' },
  { word: 'Shiba Inu', theme: 'internet', category: 'memes' },
  { word: 'Chipi Chipi Chapa Chapa', theme: 'internet', category: 'memes' },
  { word: 'Gegagedigedagedago', theme: 'internet', category: 'memes' },
  { word: 'Phonk Music', theme: 'internet', category: 'memes' },
  { word: 'Sigma Grindset', theme: 'internet', category: 'memes' },
  { word: 'Alpha Male', theme: 'internet', category: 'memes' },
  { word: 'Beta Male', theme: 'internet', category: 'memes' },
  { word: 'Omega Male', theme: 'internet', category: 'memes' },
  { word: 'Ligma', theme: 'internet', category: 'memes' },
  { word: 'Sugma', theme: 'internet', category: 'memes' },
  { word: 'Candice', theme: 'internet', category: 'memes' },
  { word: 'Joe Mama', theme: 'internet', category: 'memes' },
  { word: 'Deez Nuts', theme: 'internet', category: 'memes' },
  { word: 'Bofa', theme: 'internet', category: 'memes' },
  { word: 'Updog', theme: 'internet', category: 'memes' },
  { word: 'Wenomechainsama', theme: 'internet', category: 'memes' },
  { word: 'Bing Chilling', theme: 'internet', category: 'memes' },
  { word: 'Social Credit', theme: 'internet', category: 'memes' },
  { word: 'Zhong Xina', theme: 'internet', category: 'memes' },
  { word: 'Wok', theme: 'internet', category: 'memes' },
  { word: 'Bing Bong', theme: 'internet', category: 'memes' },
  { word: 'Glizzy', theme: 'internet', category: 'memes' },
  { word: 'Glizzy Gobbler', theme: 'internet', category: 'memes' },
  { word: 'Zesty', theme: 'internet', category: 'memes' },
  { word: 'Sassy', theme: 'internet', category: 'memes' },
  { word: 'Material Girl', theme: 'internet', category: 'memes' },
  { word: 'Girlboss', theme: 'internet', category: 'memes' },
  { word: 'Gaslight', theme: 'internet', category: 'memes' },
  { word: 'Gatekeep', theme: 'internet', category: 'memes' },
  { word: 'Slay Queen', theme: 'internet', category: 'memes' },
  { word: 'Yassify', theme: 'internet', category: 'memes' },
  { word: 'Serving', theme: 'internet', category: 'memes' },
  { word: 'Ate And Left No Crumbs', theme: 'internet', category: 'memes' },
  { word: 'Understood The Assignment', theme: 'internet', category: 'memes' },
  { word: 'Living For This', theme: 'internet', category: 'memes' },
  { word: 'Obsessed', theme: 'internet', category: 'memes' },
  { word: 'Unalive', theme: 'internet', category: 'memes' },
  { word: 'Corn', theme: 'internet', category: 'memes' },
  { word: 'Accountant', theme: 'internet', category: 'memes' },
  { word: 'Bussin No Cap', theme: 'internet', category: 'memes' },
  { word: 'Respectfully', theme: 'internet', category: 'memes' },
  { word: 'Disrespectfully', theme: 'internet', category: 'memes' },
  { word: 'Goblin Mode', theme: 'internet', category: 'memes' },
  { word: 'Feral', theme: 'internet', category: 'memes' },
  { word: 'Unhinged Era', theme: 'internet', category: 'memes' },
  { word: 'Villain Era', theme: 'internet', category: 'memes' },
  { word: 'Healing Era', theme: 'internet', category: 'memes' },
  { word: 'Soft Launch', theme: 'internet', category: 'memes' },
  { word: 'Hard Launch', theme: 'internet', category: 'memes' },
  { word: 'Situationship', theme: 'internet', category: 'memes' },
  { word: 'Talking Stage', theme: 'internet', category: 'memes' },
  { word: 'Breadcrumbing', theme: 'internet', category: 'memes' },
  { word: 'Ick List', theme: 'internet', category: 'memes' },
  { word: 'Beige Flag Energy', theme: 'internet', category: 'memes' },
];
