// Movies words

module.exports = [
  { word: 'Star Wars', theme: 'media', category: 'movies' },
  { word: 'Harry Potter', theme: 'media', category: 'movies' },
  { word: 'Marvel', theme: 'media', category: 'movies' },
  { word: 'Lord of the Rings', theme: 'media', category: 'movies' },
  { word: 'Titanic', theme: 'media', category: 'movies' },
  { word: 'Avatar', theme: 'media', category: 'movies' },
  { word: 'Jurassic Park', theme: 'media', category: 'movies' },
  { word: 'The Matrix', theme: 'media', category: 'movies' },
  { word: 'Inception', theme: 'media', category: 'movies' },
  { word: 'Frozen', theme: 'media', category: 'movies' },
  { word: 'Toy Story', theme: 'media', category: 'movies' },
  { word: 'Shrek', theme: 'media', category: 'movies' },
  { word: 'Breaking Bad', theme: 'media', category: 'movies' },
  { word: 'Game of Thrones', theme: 'media', category: 'movies' },
  { word: 'Stranger Things', theme: 'media', category: 'movies' },
  { word: 'The Office', theme: 'media', category: 'movies' },
  { word: 'Friends', theme: 'media', category: 'movies' },
  { word: 'Spongebob', theme: 'media', category: 'movies' },
  { word: 'Rick and Morty', theme: 'media', category: 'movies' },
  { word: 'Squid Game', theme: 'media', category: 'movies' },
  { word: 'The Simpsons', theme: 'media', category: 'movies' },
  { word: 'Family Guy', theme: 'media', category: 'movies' },
  { word: 'South Park', theme: 'media', category: 'movies' },
  { word: 'Futurama', theme: 'media', category: 'movies' },
  { word: 'Adventure Time', theme: 'media', category: 'movies' },
  { word: 'Regular Show', theme: 'media', category: 'movies' },
  { word: 'Gravity Falls', theme: 'media', category: 'movies' },
  { word: 'Steven Universe', theme: 'media', category: 'movies' },
  { word: 'Avatar The Last Airbender', theme: 'media', category: 'movies' },
  { word: 'Legend of Korra', theme: 'media', category: 'movies' },
  { word: 'Teen Titans', theme: 'media', category: 'movies' },
  { word: 'Ben 10', theme: 'media', category: 'movies' },
  { word: 'Danny Phantom', theme: 'media', category: 'movies' },
  { word: 'Kim Possible', theme: 'media', category: 'movies' },
  { word: 'Phineas and Ferb', theme: 'media', category: 'movies' },
  { word: 'Fairly OddParents', theme: 'media', category: 'movies' },
  { word: 'Jimmy Neutron', theme: 'media', category: 'movies' },
  { word: 'Rugrats', theme: 'media', category: 'movies' },
  { word: 'Hey Arnold', theme: 'media', category: 'movies' },
  { word: 'Courage the Cowardly Dog', theme: 'media', category: 'movies' },
  { word: 'Ed Edd n Eddy', theme: 'media', category: 'movies' },
  { word: 'Dexter Laboratory', theme: 'media', category: 'movies' },
  { word: 'Powerpuff Girls', theme: 'media', category: 'movies' },
  { word: 'Samurai Jack', theme: 'media', category: 'movies' },
  { word: 'Johnny Bravo', theme: 'media', category: 'movies' },
  { word: 'Scooby-Doo', theme: 'media', category: 'movies' },
  { word: 'Tom and Jerry', theme: 'media', category: 'movies' },
  { word: 'Looney Tunes', theme: 'media', category: 'movies' },
  { word: 'Batman', theme: 'media', category: 'movies' },
  { word: 'Superman', theme: 'media', category: 'movies' },
  { word: 'Spider-Man', theme: 'media', category: 'movies' },
  { word: 'Iron Man', theme: 'media', category: 'movies' },
  { word: 'Captain America', theme: 'media', category: 'movies' },
  { word: 'Thor', theme: 'media', category: 'movies' },
  { word: 'Hulk', theme: 'media', category: 'movies' },
  { word: 'Black Widow', theme: 'media', category: 'movies' },
  { word: 'Avengers', theme: 'media', category: 'movies' },
  { word: 'X-Men', theme: 'media', category: 'movies' },
  { word: 'Deadpool', theme: 'media', category: 'movies' },
  { word: 'Wolverine', theme: 'media', category: 'movies' },
  { word: 'Guardians of the Galaxy', theme: 'media', category: 'movies' },
  { word: 'Black Panther', theme: 'media', category: 'movies' },
  { word: 'Doctor Strange', theme: 'media', category: 'movies' },
  { word: 'Ant-Man', theme: 'media', category: 'movies' },
  { word: 'The Mandalorian', theme: 'media', category: 'movies' },
  { word: 'Baby Yoda', theme: 'media', category: 'movies' },
  { word: 'Darth Vader', theme: 'media', category: 'movies' },
  { word: 'Luke Skywalker', theme: 'media', category: 'movies' },
  { word: 'Princess Leia', theme: 'media', category: 'movies' },
  { word: 'Han Solo', theme: 'media', category: 'movies' },
  { word: 'Chewbacca', theme: 'media', category: 'movies' },
  { word: 'Yoda', theme: 'media', category: 'movies' },
  { word: 'Obi-Wan Kenobi', theme: 'media', category: 'movies' },
  { word: 'Anakin Skywalker', theme: 'media', category: 'movies' },
  { word: 'Padme', theme: 'media', category: 'movies' },
  { word: 'Rey', theme: 'media', category: 'movies' },
  { word: 'Kylo Ren', theme: 'media', category: 'movies' },
  { word: 'The Hobbit', theme: 'media', category: 'movies' },
  { word: 'Frodo', theme: 'media', category: 'movies' },
  { word: 'Gandalf', theme: 'media', category: 'movies' },
  { word: 'Aragorn', theme: 'media', category: 'movies' },
  { word: 'Legolas', theme: 'media', category: 'movies' },
  { word: 'Gimli', theme: 'media', category: 'movies' },
  { word: 'Gollum', theme: 'media', category: 'movies' },
  { word: 'Sauron', theme: 'media', category: 'movies' },
  { word: 'Dumbledore', theme: 'media', category: 'movies' },
  { word: 'Voldemort', theme: 'media', category: 'movies' },
  { word: 'Hermione', theme: 'media', category: 'movies' },
  { word: 'Ron Weasley', theme: 'media', category: 'movies' },
  { word: 'Snape', theme: 'media', category: 'movies' },
  { word: 'Hagrid', theme: 'media', category: 'movies' },
  { word: 'Dobby', theme: 'media', category: 'movies' },
  { word: 'Draco Malfoy', theme: 'media', category: 'movies' },
  { word: 'The Walking Dead', theme: 'media', category: 'movies' },
  { word: 'Lost', theme: 'media', category: 'movies' },
  { word: 'Prison Break', theme: 'media', category: 'movies' },
  { word: 'Dexter', theme: 'media', category: 'movies' },
  { word: 'House', theme: 'media', category: 'movies' },
  { word: 'Sherlock', theme: 'media', category: 'movies' },
  { word: 'Doctor Who', theme: 'media', category: 'movies' },
];
