// Music words

module.exports = [
  { word: 'piano', theme: 'artist', category: 'music' },
  { word: 'Taylor Swift', theme: 'artist', category: 'music' },
  { word: 'Drake', theme: 'artist', category: 'music' },
  { word: 'Beyonce', theme: 'artist', category: 'music' },
  { word: 'The Weeknd', theme: 'artist', category: 'music' },
  { word: 'Billie Eilish', theme: 'artist', category: 'music' },
  { word: 'Ed Sheeran', theme: 'artist', category: 'music' },
  { word: 'Ariana Grande', theme: 'artist', category: 'music' },
  { word: 'Post Malone', theme: 'artist', category: 'music' },
  { word: 'Dua Lipa', theme: 'artist', category: 'music' },
  { word: 'Bad Bunny', theme: 'artist', category: 'music' },
  { word: 'BTS', theme: 'artist', category: 'music' },
  { word: 'Olivia Rodrigo', theme: 'artist', category: 'music' },
  { word: 'Harry Styles', theme: 'artist', category: 'music' },
  { word: 'Doja Cat', theme: 'artist', category: 'music' },
  { word: 'Travis Scott', theme: 'artist', category: 'music' },
  { word: 'Kanye West', theme: 'artist', category: 'music' },
  { word: 'Eminem', theme: 'artist', category: 'music' },
  { word: 'Rihanna', theme: 'artist', category: 'music' },
  { word: 'Lady Gaga', theme: 'artist', category: 'music' },
  { word: 'Bruno Mars', theme: 'artist', category: 'music' },
  { word: 'Adele', theme: 'artist', category: 'music' },
  { word: 'Coldplay', theme: 'artist', category: 'music' },
  { word: 'Imagine Dragons', theme: 'artist', category: 'music' },
  { word: 'Twenty One Pilots', theme: 'artist', category: 'music' },
  { word: 'Maroon 5', theme: 'artist', category: 'music' },
  { word: 'OneRepublic', theme: 'artist', category: 'music' },
  { word: 'The Chainsmokers', theme: 'artist', category: 'music' },
  { word: 'Marshmello', theme: 'artist', category: 'music' },
  { word: 'Calvin Harris', theme: 'artist', category: 'music' },
  { word: 'David Guetta', theme: 'artist', category: 'music' },
  { word: 'Avicii', theme: 'artist', category: 'music' },
  { word: 'Skrillex', theme: 'artist', category: 'music' },
  { word: 'Deadmau5', theme: 'artist', category: 'music' },
  { word: 'Diplo', theme: 'artist', category: 'music' },
  { word: 'Zedd', theme: 'artist', category: 'music' },
  { word: 'Tiesto', theme: 'artist', category: 'music' },
  { word: 'Martin Garrix', theme: 'artist', category: 'music' },
  { word: 'Kygo', theme: 'artist', category: 'music' },
  { word: 'Alan Walker', theme: 'artist', category: 'music' },
  { word: 'Daft Punk', theme: 'artist', category: 'music' },
  { word: 'Justice', theme: 'artist', category: 'music' },
  { word: 'Disclosure', theme: 'artist', category: 'music' },
  { word: 'ODESZA', theme: 'artist', category: 'music' },
  { word: 'Flume', theme: 'artist', category: 'music' },
  { word: 'Porter Robinson', theme: 'artist', category: 'music' },
  { word: 'Madeon', theme: 'artist', category: 'music' },
  { word: 'Illenium', theme: 'artist', category: 'music' },
  { word: 'Seven Lions', theme: 'artist', category: 'music' },
  { word: 'Excision', theme: 'artist', category: 'music' },
  { word: 'Bassnectar', theme: 'artist', category: 'music' },
  { word: 'Kendrick Lamar', theme: 'artist', category: 'music' },
  { word: 'J Cole', theme: 'artist', category: 'music' },
  { word: 'Lil Wayne', theme: 'artist', category: 'music' },
  { word: 'Nicki Minaj', theme: 'artist', category: 'music' },
  { word: 'Cardi B', theme: 'artist', category: 'music' },
  { word: 'Megan Thee Stallion', theme: 'artist', category: 'music' },
  { word: 'Lil Nas X', theme: 'artist', category: 'music' },
  { word: 'Tyler The Creator', theme: 'artist', category: 'music' },
  { word: 'Frank Ocean', theme: 'artist', category: 'music' },
  { word: 'The Weeknd', theme: 'artist', category: 'music' },
  { word: 'SZA', theme: 'artist', category: 'music' },
  { word: 'H.E.R.', theme: 'artist', category: 'music' },
  { word: 'Khalid', theme: 'artist', category: 'music' },
  { word: 'Shawn Mendes', theme: 'artist', category: 'music' },
  { word: 'Justin Bieber', theme: 'artist', category: 'music' },
  { word: 'Selena Gomez', theme: 'artist', category: 'music' },
  { word: 'Demi Lovato', theme: 'artist', category: 'music' },
  { word: 'Miley Cyrus', theme: 'artist', category: 'music' },
  { word: 'Katy Perry', theme: 'artist', category: 'music' },
  { word: 'Britney Spears', theme: 'artist', category: 'music' },
  { word: 'Christina Aguilera', theme: 'artist', category: 'music' },
  { word: 'Pink', theme: 'artist', category: 'music' },
  { word: 'Shakira', theme: 'artist', category: 'music' },
  { word: 'Jennifer Lopez', theme: 'artist', category: 'music' },
  { word: 'Madonna', theme: 'artist', category: 'music' },
  { word: 'Cher', theme: 'artist', category: 'music' },
  { word: 'Elton John', theme: 'artist', category: 'music' },
  { word: 'Billy Joel', theme: 'artist', category: 'music' },
  { word: 'Stevie Wonder', theme: 'artist', category: 'music' },
  { word: 'Prince', theme: 'artist', category: 'music' },
  { word: 'Michael Jackson', theme: 'artist', category: 'music' },
  { word: 'Whitney Houston', theme: 'artist', category: 'music' },
  { word: 'Mariah Carey', theme: 'artist', category: 'music' },
  { word: 'Celine Dion', theme: 'artist', category: 'music' },
  { word: 'The Beatles', theme: 'artist', category: 'music' },
  { word: 'The Rolling Stones', theme: 'artist', category: 'music' },
  { word: 'Led Zeppelin', theme: 'artist', category: 'music' },
  { word: 'Pink Floyd', theme: 'artist', category: 'music' },
  { word: 'Queen', theme: 'artist', category: 'music' },
  { word: 'AC/DC', theme: 'artist', category: 'music' },
  { word: 'Metallica', theme: 'artist', category: 'music' },
  { word: 'Nirvana', theme: 'artist', category: 'music' },
  { word: 'Foo Fighters', theme: 'artist', category: 'music' },
  { word: 'Green Day', theme: 'artist', category: 'music' },
  { word: 'Blink-182', theme: 'artist', category: 'music' },
  { word: 'Linkin Park', theme: 'artist', category: 'music' },
  { word: 'Red Hot Chili Peppers', theme: 'artist', category: 'music' },
  { word: 'Radiohead', theme: 'artist', category: 'music' },
  { word: 'Muse', theme: 'artist', category: 'music' },
  { word: 'Arctic Monkeys', theme: 'artist', category: 'music' },
  { word: 'The Strokes', theme: 'artist', category: 'music' },
  { word: 'The Killers', theme: 'artist', category: 'music' },
  { word: 'Fall Out Boy', theme: 'artist', category: 'music' },
  { word: 'Panic at the Disco', theme: 'artist', category: 'music' },
  { word: 'My Chemical Romance', theme: 'artist', category: 'music' },
  { word: 'Paramore', theme: 'artist', category: 'music' },
  { word: 'Evanescence', theme: 'artist', category: 'music' },
  { word: 'Fleetwood Mac', theme: 'artist', category: 'music' },
  { word: 'Eagles', theme: 'artist', category: 'music' },
  { word: 'Journey', theme: 'artist', category: 'music' },
  { word: 'Boston', theme: 'artist', category: 'music' },
  { word: 'Toto', theme: 'artist', category: 'music' },
  { word: 'U2', theme: 'artist', category: 'music' },
  { word: 'R.E.M.', theme: 'artist', category: 'music' },
  { word: 'Oasis', theme: 'artist', category: 'music' },
  { word: 'Blur', theme: 'artist', category: 'music' },
  { word: 'The Smiths', theme: 'artist', category: 'music' },
  { word: 'Joy Division', theme: 'artist', category: 'music' },
  { word: 'New Order', theme: 'artist', category: 'music' },
  { word: 'Depeche Mode', theme: 'artist', category: 'music' },
  { word: 'The Cure', theme: 'artist', category: 'music' },
  { word: 'Duran Duran', theme: 'artist', category: 'music' },
];
