// Places words

module.exports = [
  { word: 'library', theme: 'location', category: 'places' },
  { word: 'theater', theme: 'location', category: 'places' },
  { word: 'museum', theme: 'location', category: 'places' },
  { word: 'stadium', theme: 'location', category: 'places' },
  { word: 'airport', theme: 'location', category: 'places' },
  { word: 'hospital', theme: 'location', category: 'places' },
  { word: 'school', theme: 'location', category: 'places' },
  { word: 'university', theme: 'location', category: 'places' },
  { word: 'college', theme: 'location', category: 'places' },
  { word: 'church', theme: 'location', category: 'places' },
  { word: 'temple', theme: 'location', category: 'places' },
  { word: 'mosque', theme: 'location', category: 'places' },
  { word: 'synagogue', theme: 'location', category: 'places' },
  { word: 'castle', theme: 'location', category: 'places' },
  { word: 'palace', theme: 'location', category: 'places' },
  { word: 'mansion', theme: 'location', category: 'places' },
  { word: 'house', theme: 'location', category: 'places' },
  { word: 'apartment', theme: 'location', category: 'places' },
  { word: 'hotel', theme: 'location', category: 'places' },
  { word: 'motel', theme: 'location', category: 'places' },
  { word: 'restaurant', theme: 'location', category: 'places' },
  { word: 'cafe', theme: 'location', category: 'places' },
  { word: 'bakery', theme: 'location', category: 'places' },
  { word: 'grocery store', theme: 'location', category: 'places' },
  { word: 'mall', theme: 'location', category: 'places' },
  { word: 'market', theme: 'location', category: 'places' },
  { word: 'park', theme: 'location', category: 'places' },
  { word: 'playground', theme: 'location', category: 'places' },
  { word: 'zoo', theme: 'location', category: 'places' },
  { word: 'aquarium', theme: 'location', category: 'places' },
  { word: 'beach', theme: 'location', category: 'places' },
  { word: 'pool', theme: 'location', category: 'places' },
  { word: 'gym', theme: 'location', category: 'places' },
  { word: 'spa', theme: 'location', category: 'places' },
  { word: 'salon', theme: 'location', category: 'places' },
  { word: 'barbershop', theme: 'location', category: 'places' },
  { word: 'bank', theme: 'location', category: 'places' },
  { word: 'post office', theme: 'location', category: 'places' },
  { word: 'police station', theme: 'location', category: 'places' },
  { word: 'fire station', theme: 'location', category: 'places' },
  { word: 'gas station', theme: 'location', category: 'places' },
  { word: 'train station', theme: 'location', category: 'places' },
  { word: 'bus stop', theme: 'location', category: 'places' },
  { word: 'subway', theme: 'location', category: 'places' },
  { word: 'parking lot', theme: 'location', category: 'places' },
  { word: 'garage', theme: 'location', category: 'places' },
  { word: 'warehouse', theme: 'location', category: 'places' },
  { word: 'factory', theme: 'location', category: 'places' },
  { word: 'office', theme: 'location', category: 'places' },
  { word: 'skyscraper', theme: 'location', category: 'places' },
];
