// Sports words

module.exports = [
  { word: 'soccer', theme: 'activity', category: 'sports' },
  { word: 'football', theme: 'activity', category: 'sports' },
  { word: 'basketball', theme: 'activity', category: 'sports' },
  { word: 'baseball', theme: 'activity', category: 'sports' },
  { word: 'tennis', theme: 'activity', category: 'sports' },
  { word: 'volleyball', theme: 'activity', category: 'sports' },
  { word: 'golf', theme: 'activity', category: 'sports' },
  { word: 'hockey', theme: 'activity', category: 'sports' },
  { word: 'cricket', theme: 'activity', category: 'sports' },
  { word: 'rugby', theme: 'activity', category: 'sports' },
  { word: 'bowling', theme: 'activity', category: 'sports' },
  { word: 'boxing', theme: 'activity', category: 'sports' },
  { word: 'wrestling', theme: 'activity', category: 'sports' },
  { word: 'MMA', theme: 'activity', category: 'sports' },
  { word: 'karate', theme: 'activity', category: 'sports' },
  { word: 'judo', theme: 'activity', category: 'sports' },
  { word: 'taekwondo', theme: 'activity', category: 'sports' },
  { word: 'fencing', theme: 'activity', category: 'sports' },
  { word: 'archery', theme: 'activity', category: 'sports' },
  { word: 'swimming', theme: 'activity', category: 'sports' },
  { word: 'diving', theme: 'activity', category: 'sports' },
  { word: 'surfing', theme: 'activity', category: 'sports' },
  { word: 'skiing', theme: 'activity', category: 'sports' },
  { word: 'snowboarding', theme: 'activity', category: 'sports' },
  { word: 'ice skating', theme: 'activity', category: 'sports' },
  { word: 'figure skating', theme: 'activity', category: 'sports' },
  { word: 'speed skating', theme: 'activity', category: 'sports' },
  { word: 'curling', theme: 'activity', category: 'sports' },
  { word: 'bobsled', theme: 'activity', category: 'sports' },
  { word: 'skeleton', theme: 'activity', category: 'sports' },
  { word: 'biathlon', theme: 'activity', category: 'sports' },
  { word: 'triathlon', theme: 'activity', category: 'sports' },
  { word: 'marathon', theme: 'activity', category: 'sports' },
  { word: 'sprinting', theme: 'activity', category: 'sports' },
  { word: 'hurdles', theme: 'activity', category: 'sports' },
  { word: 'long jump', theme: 'activity', category: 'sports' },
  { word: 'high jump', theme: 'activity', category: 'sports' },
  { word: 'pole vault', theme: 'activity', category: 'sports' },
  { word: 'shot put', theme: 'activity', category: 'sports' },
  { word: 'discus', theme: 'activity', category: 'sports' },
  { word: 'javelin', theme: 'activity', category: 'sports' },
  { word: 'hammer throw', theme: 'activity', category: 'sports' },
  { word: 'gymnastics', theme: 'activity', category: 'sports' },
  { word: 'cheerleading', theme: 'activity', category: 'sports' },
  { word: 'dance', theme: 'activity', category: 'sports' },
  { word: 'ballet', theme: 'activity', category: 'sports' },
  { word: 'yoga', theme: 'activity', category: 'sports' },
  { word: 'pilates', theme: 'activity', category: 'sports' },
  { word: 'crossfit', theme: 'activity', category: 'sports' },
  { word: 'weightlifting', theme: 'activity', category: 'sports' },
  { word: 'powerlifting', theme: 'activity', category: 'sports' },
  { word: 'bodybuilding', theme: 'activity', category: 'sports' },
  { word: 'cycling', theme: 'activity', category: 'sports' },
  { word: 'BMX', theme: 'activity', category: 'sports' },
  { word: 'mountain biking', theme: 'activity', category: 'sports' },
  { word: 'rock climbing', theme: 'activity', category: 'sports' },
  { word: 'parkour', theme: 'activity', category: 'sports' },
];
