// Technology words

module.exports = [
  { word: 'iPhone', theme: 'tech', category: 'technology' },
  { word: 'laptop', theme: 'tech', category: 'technology' },
  { word: 'robot', theme: 'tech', category: 'technology' },
  { word: 'smartphone', theme: 'tech', category: 'technology' },
  { word: 'headphones', theme: 'tech', category: 'technology' },
  { word: 'drone', theme: 'tech', category: 'technology' },
  { word: 'keyboard', theme: 'tech', category: 'technology' },
  { word: 'mouse', theme: 'tech', category: 'technology' },
  { word: 'monitor', theme: 'tech', category: 'technology' },
  { word: 'television', theme: 'tech', category: 'technology' },
  { word: 'camera', theme: 'tech', category: 'technology' },
  { word: 'Tesla', theme: 'tech', category: 'technology' },
  { word: 'WiFi', theme: 'tech', category: 'technology' },
  { word: 'Bluetooth', theme: 'tech', category: 'technology' },
  { word: 'USB', theme: 'tech', category: 'technology' },
  { word: 'VR headset', theme: 'tech', category: 'technology' },
  { word: 'smartwatch', theme: 'tech', category: 'technology' },
  { word: 'tablet', theme: 'tech', category: 'technology' },
  { word: 'speaker', theme: 'tech', category: 'technology' },
  { word: 'microphone', theme: 'tech', category: 'technology' },
  { word: 'webcam', theme: 'tech', category: 'technology' },
  { word: 'printer', theme: 'tech', category: 'technology' },
  { word: 'scanner', theme: 'tech', category: 'technology' },
  { word: 'router', theme: 'tech', category: 'technology' },
  { word: 'modem', theme: 'tech', category: 'technology' },
  { word: 'hard drive', theme: 'tech', category: 'technology' },
  { word: 'SSD', theme: 'tech', category: 'technology' },
  { word: 'RAM', theme: 'tech', category: 'technology' },
  { word: 'CPU', theme: 'tech', category: 'technology' },
  { word: 'GPU', theme: 'tech', category: 'technology' },
  { word: 'motherboard', theme: 'tech', category: 'technology' },
  { word: 'power supply', theme: 'tech', category: 'technology' },
  { word: 'cooling fan', theme: 'tech', category: 'technology' },
  { word: 'battery', theme: 'tech', category: 'technology' },
  { word: 'charger', theme: 'tech', category: 'technology' },
  { word: 'cable', theme: 'tech', category: 'technology' },
  { word: 'adapter', theme: 'tech', category: 'technology' },
  { word: 'remote control', theme: 'tech', category: 'technology' },
  { word: 'game controller', theme: 'tech', category: 'technology' },
  { word: 'joystick', theme: 'tech', category: 'technology' },
  { word: 'steering wheel', theme: 'tech', category: 'technology' },
  { word: 'flight stick', theme: 'tech', category: 'technology' },
];
