// Videogames words

module.exports = [
  { word: 'Minecraft', theme: 'game', category: 'videogames' },
  { word: 'Fortnite', theme: 'game', category: 'videogames' },
  { word: 'Pokemon', theme: 'game', category: 'videogames' },
  { word: 'Mario', theme: 'game', category: 'videogames' },
  { word: 'Zelda', theme: 'game', category: 'videogames' },
  { word: 'Sonic', theme: 'game', category: 'videogames' },
  { word: 'Tetris', theme: 'game', category: 'videogames' },
  { word: 'Roblox', theme: 'game', category: 'videogames' },
  { word: 'Among Us', theme: 'game', category: 'videogames' },
  { word: 'Valorant', theme: 'game', category: 'videogames' },
  { word: 'Overwatch', theme: 'game', category: 'videogames' },
  { word: 'League of Legends', theme: 'game', category: 'videogames' },
  { word: 'Dota', theme: 'game', category: 'videogames' },
  { word: 'Call of Duty', theme: 'game', category: 'videogames' },
  { word: 'Battlefield', theme: 'game', category: 'videogames' },
  { word: 'GTA', theme: 'game', category: 'videogames' },
  { word: 'Skyrim', theme: 'game', category: 'videogames' },
  { word: 'Halo', theme: 'game', category: 'videogames' },
  { word: 'Apex Legends', theme: 'game', category: 'videogames' },
  { word: 'Rocket League', theme: 'game', category: 'videogames' },
  { word: 'Fall Guys', theme: 'game', category: 'videogames' },
  { word: 'Stardew Valley', theme: 'game', category: 'videogames' },
  { word: 'Animal Crossing', theme: 'game', category: 'videogames' },
  { word: 'Sims', theme: 'game', category: 'videogames' },
  { word: 'Undertale', theme: 'game', category: 'videogames' },
  { word: 'Hollow Knight', theme: 'game', category: 'videogames' },
  { word: 'Dark Souls', theme: 'game', category: 'videogames' },
  { word: 'Elden Ring', theme: 'game', category: 'videogames' },
  { word: 'Cyberpunk', theme: 'game', category: 'videogames' },
  { word: 'Witcher', theme: 'game', category: 'videogames' },
  { word: 'Red Dead Redemption', theme: 'game', category: 'videogames' },
  { word: 'Assassins Creed', theme: 'game', category: 'videogames' },
  { word: 'God of War', theme: 'game', category: 'videogames' },
  { word: 'Spider-Man', theme: 'game', category: 'videogames' },
  { word: 'Batman Arkham', theme: 'game', category: 'videogames' },
  { word: 'Uncharted', theme: 'game', category: 'videogames' },
  { word: 'Last of Us', theme: 'game', category: 'videogames' },
  { word: 'Resident Evil', theme: 'game', category: 'videogames' },
  { word: 'Silent Hill', theme: 'game', category: 'videogames' },
  { word: 'Dead Space', theme: 'game', category: 'videogames' },
  { word: 'Outlast', theme: 'game', category: 'videogames' },
  { word: 'Five Nights at Freddys', theme: 'game', category: 'videogames' },
  { word: 'Phasmophobia', theme: 'game', category: 'videogames' },
  { word: 'Portal', theme: 'game', category: 'videogames' },
  { word: 'Half-Life', theme: 'game', category: 'videogames' },
  { word: 'Counter-Strike', theme: 'game', category: 'videogames' },
  { word: 'Team Fortress', theme: 'game', category: 'videogames' },
  { word: 'Left 4 Dead', theme: 'game', category: 'videogames' },
  { word: 'Payday', theme: 'game', category: 'videogames' },
  { word: 'Destiny', theme: 'game', category: 'videogames' },
  { word: 'Borderlands', theme: 'game', category: 'videogames' },
  { word: 'Bioshock', theme: 'game', category: 'videogames' },
  { word: 'Fallout', theme: 'game', category: 'videogames' },
  { word: 'Mass Effect', theme: 'game', category: 'videogames' },
  { word: 'Dragon Age', theme: 'game', category: 'videogames' },
  { word: 'Final Fantasy', theme: 'game', category: 'videogames' },
  { word: 'Kingdom Hearts', theme: 'game', category: 'videogames' },
  { word: 'Persona', theme: 'game', category: 'videogames' },
  { word: 'Chrono Trigger', theme: 'game', category: 'videogames' },
  { word: 'Earthbound', theme: 'game', category: 'videogames' },
  { word: 'Metal Gear', theme: 'game', category: 'videogames' },
  { word: 'Splinter Cell', theme: 'game', category: 'videogames' },
  { word: 'Hitman', theme: 'game', category: 'videogames' },
  { word: 'Dishonored', theme: 'game', category: 'videogames' },
  { word: 'Thief', theme: 'game', category: 'videogames' },
  { word: 'Deus Ex', theme: 'game', category: 'videogames' },
  { word: 'System Shock', theme: 'game', category: 'videogames' },
  { word: 'Prey', theme: 'game', category: 'videogames' },
  { word: 'Doom', theme: 'game', category: 'videogames' },
  { word: 'Quake', theme: 'game', category: 'videogames' },
  { word: 'Wolfenstein', theme: 'game', category: 'videogames' },
  { word: 'Metroid', theme: 'game', category: 'videogames' },
  { word: 'Castlevania', theme: 'game', category: 'videogames' },
  { word: 'Mega Man', theme: 'game', category: 'videogames' },
  { word: 'Kirby', theme: 'game', category: 'videogames' },
  { word: 'Donkey Kong', theme: 'game', category: 'videogames' },
  { word: 'Crash Bandicoot', theme: 'game', category: 'videogames' },
  { word: 'Spyro', theme: 'game', category: 'videogames' },
  { word: 'Ratchet and Clank', theme: 'game', category: 'videogames' },
  { word: 'Jak and Daxter', theme: 'game', category: 'videogames' },
  { word: 'Sly Cooper', theme: 'game', category: 'videogames' },
  { word: 'Rayman', theme: 'game', category: 'videogames' },
  { word: 'Banjo-Kazooie', theme: 'game', category: 'videogames' },
  { word: 'Yoshi', theme: 'game', category: 'videogames' },
  { word: 'Luigi', theme: 'game', category: 'videogames' },
  { word: 'Wario', theme: 'game', category: 'videogames' },
  { word: 'Pac-Man', theme: 'game', category: 'videogames' },
  { word: 'Space Invaders', theme: 'game', category: 'videogames' },
  { word: 'Galaga', theme: 'game', category: 'videogames' },
  { word: 'Asteroids', theme: 'game', category: 'videogames' },
  { word: 'Pong', theme: 'game', category: 'videogames' },
  { word: 'Street Fighter', theme: 'game', category: 'videogames' },
  { word: 'Mortal Kombat', theme: 'game', category: 'videogames' },
  { word: 'Tekken', theme: 'game', category: 'videogames' },
  { word: 'Smash Bros', theme: 'game', category: 'videogames' },
  { word: 'Guilty Gear', theme: 'game', category: 'videogames' },
  { word: 'BlazBlue', theme: 'game', category: 'videogames' },
  { word: 'Dragon Ball FighterZ', theme: 'game', category: 'videogames' },
  { word: 'Naruto', theme: 'game', category: 'videogames' },
  { word: 'One Piece', theme: 'game', category: 'videogames' },
  { word: 'FIFA', theme: 'game', category: 'videogames' },
  { word: 'Madden', theme: 'game', category: 'videogames' },
  { word: 'NBA 2K', theme: 'game', category: 'videogames' },
  { word: 'MLB The Show', theme: 'game', category: 'videogames' },
  { word: 'NHL', theme: 'game', category: 'videogames' },
  { word: 'Tony Hawk', theme: 'game', category: 'videogames' },
  { word: 'Skate', theme: 'game', category: 'videogames' },
  { word: 'Gran Turismo', theme: 'game', category: 'videogames' },
  { word: 'Forza', theme: 'game', category: 'videogames' },
  { word: 'Need for Speed', theme: 'game', category: 'videogames' },
  { word: 'Mario Kart', theme: 'game', category: 'videogames' },
  { word: 'Burnout', theme: 'game', category: 'videogames' },
  { word: 'F-Zero', theme: 'game', category: 'videogames' },
  { word: 'Wipeout', theme: 'game', category: 'videogames' },
  { word: 'Civilization', theme: 'game', category: 'videogames' },
  { word: 'Age of Empires', theme: 'game', category: 'videogames' },
  { word: 'StarCraft', theme: 'game', category: 'videogames' },
  { word: 'Warcraft', theme: 'game', category: 'videogames' },
  { word: 'Command and Conquer', theme: 'game', category: 'videogames' },
  { word: 'Total War', theme: 'game', category: 'videogames' },
  { word: 'XCOM', theme: 'game', category: 'videogames' },
  { word: 'Fire Emblem', theme: 'game', category: 'videogames' },
  { word: 'Advance Wars', theme: 'game', category: 'videogames' },
  { word: 'Chess', theme: 'game', category: 'videogames' },
  { word: 'Hearthstone', theme: 'game', category: 'videogames' },
  { word: 'Magic The Gathering', theme: 'game', category: 'videogames' },
  { word: 'Yu-Gi-Oh', theme: 'game', category: 'videogames' },
  { word: 'Solitaire', theme: 'game', category: 'videogames' },
  { word: 'Minesweeper', theme: 'game', category: 'videogames' },
  { word: 'Sudoku', theme: 'game', category: 'videogames' },
  { word: 'Candy Crush', theme: 'game', category: 'videogames' },
  { word: 'Bejeweled', theme: 'game', category: 'videogames' },
  { word: 'Angry Birds', theme: 'game', category: 'videogames' },
  { word: 'Cut the Rope', theme: 'game', category: 'videogames' },
  { word: 'Plants vs Zombies', theme: 'game', category: 'videogames' },
  { word: 'Bloons', theme: 'game', category: 'videogames' },
  { word: 'Terraria', theme: 'game', category: 'videogames' },
  { word: 'Starbound', theme: 'game', category: 'videogames' },
  { word: 'Rust', theme: 'game', category: 'videogames' },
  { word: 'ARK', theme: 'game', category: 'videogames' },
  { word: 'Subnautica', theme: 'game', category: 'videogames' },
  { word: 'The Forest', theme: 'game', category: 'videogames' },
  { word: 'Dont Starve', theme: 'game', category: 'videogames' },
  { word: 'Valheim', theme: 'game', category: 'videogames' },
  { word: 'Satisfactory', theme: 'game', category: 'videogames' },
  { word: 'Factorio', theme: 'game', category: 'videogames' },
  { word: 'Rimworld', theme: 'game', category: 'videogames' },
  { word: 'Dwarf Fortress', theme: 'game', category: 'videogames' },
  { word: 'Cities Skylines', theme: 'game', category: 'videogames' },
  { word: 'SimCity', theme: 'game', category: 'videogames' },
  { word: 'Roller Coaster Tycoon', theme: 'game', category: 'videogames' },
  { word: 'Planet Coaster', theme: 'game', category: 'videogames' },
  { word: 'Zoo Tycoon', theme: 'game', category: 'videogames' },
  { word: 'Flight Simulator', theme: 'game', category: 'videogames' },
  { word: 'Euro Truck Simulator', theme: 'game', category: 'videogames' },
  { word: 'Farming Simulator', theme: 'game', category: 'videogames' },
];
